In [798]:
import numpy as np
import math

t = 0  # number of this round
T = 8000  # numbers of rounds
l = 30  # ||a|| <= L
d = 3 #dimension of arm
m = 1 #||theta|| < m
theta_stimato = [0.0, 0.0, 0.0] #np.array([])  theta
A = [] #collector of arm
num_arms = 0 #number of arms
num_theta = 0 #num theta
Th = [] #collector of theta
W = [] #distribution of probability to play arms
N = [] #number of times an arm is played
R = [] #collection of reward
H = [] #collection of hedge losses
L = [] #collection of losses
Mixability_Gap = [] #collection of all mixability gap at each t
AI = [] #number of the arm played at time I
nu = 0.01 #regularization paramether
eta = 0.8 #learning paramether
theta_vero = [0]*6
curr_answ = 0

sample_correct = [0]*800
error_reward = [0]*800
error_best_choosen = [0] * 800

Y = []
num_arms_y = 0

M = [] #world
num_M = 0

class world():
    matrix = np.array([])
    id

    def __init__(self, param):
        self.matrix = param
        global M, num_M
        self.id = num_M
        M.append(self)
        num_M +=1
        
class arm_y():
    arm_vector = np.array([])
    id = 0

    def __init__(self, vector):
        self.arm_vector = vector
        global num_arms_y, arm_Y
        Y.append(self)
        self.id = num_arms_y
        num_arms_y += 1
        
def create_theta():
    for i in range (0, num_arms_y):
        new_theta = theta(np.matmul(M[0].matrix, Y[i].arm_vector))

def normalize(v):
    sum = np.sum(v)
    if sum > 0:
        return v / sum
    else:
        return np.array([0.33]*len(v))
    
class theta():
    vector = np.array([])
    best_arm = -1
    id

    def __init__(self, param):
        self.vector = param
        global Th, num_theta
        self.id = num_theta
        Th.append(self)
        num_theta +=1
        #i = 0
        #best = -5
        #while i < num_arms:
            #tmp = np.dot( A[i].arm_vector, np.transpose(self.vector))
            #if best < tmp:
                #best = tmp
                #self.best_arm = i

class arm():
    arm_vector = np.array([])
    id = 0
    best_theta = -1
    regret_y = []

    def __init__(self, vector):
        self.regret_y = [0] *num_arms_y
        self.arm_vector = vector
        global num_arms, A
        A.append(self)
        W.append(0)
        N.append(0)
        L.append(1)
        self.id = num_arms
        num_arms +=1
        max = -5
        for i in range (0, num_theta):
            tmp = np.matmul(self.arm_vector, Th[i].vector)
            if tmp > max:
                self.best_theta = i
                max = tmp
                            
    def new_theta_vero(self):
        min = 1000000000000000
        curr = -1
        for i in range (0, num_arms_y):
            if self.regret_y[i] < min:
                curr = i
                min = self.regret_y[i]
        global theta_vero
        theta_vero[self.id] = curr
                    
    def pull_arm(self):
        r = np.dot(self.arm_vector, np.transpose(Th[theta_vero[self.id]].vector)) + np.random.normal(0, 1)
        R.append(r)
        #print("self.id", self.id)
        #print("theta_vero", theta_vero)
        #print("regret_y", self.regret_y)
        self.regret_y[theta_vero[self.id]] += (4*(l**2)*(m**2) - r)/1000
        self.new_theta_vero()
        N[self.id] += 1
        AI.append(self.id)
        return r
        
    def norm(self):
        return np.linalg.norm(self.arm_vector)

def design_matrix(w):
    V = []
    i = 0
    while i < num_arms:
        b = [A[i].arm_vector]
        a = np.swapaxes(b, 0, 1)
        ris = np.matmul(a, b) * w[i]
        if (i == 0):
            V = ris
        else:
            V += ris
        i+=1
    return V

def norm_2_mat(x, V):
    b = [x]
    a = np.swapaxes(b, 0, 1)
    ris = np.sqrt(np.matmul(np.matmul(b,V),a))
    return ris[0][0]

def arm_to_play():
    diff = np.array(N) - np.array(W)
    i = 0
    arm = 0
    min = +5000
    while i < num_arms:
        if diff[i] < min:
            min = diff[i]
            arm = i
        i += 1
    return arm

def stima_theta():
    V = design_matrix(N)
    I = np.identity(d)
    p = np.linalg.inv(V + nu*I)
    sum = 0
    for i in range (0, t):
        sum += R[i] * np.array(A[AI[i]].arm_vector)
    #print("sum", sum)
    #print("p", p)
    res = np.matmul(p, sum)
    #print("res", res)
    global theta_stimato
    theta_stimato = res
    return res

def best_answer():
    max = -100
    best = -1
    for i in range (0, num_arms):
        curr = np.matmul(A[i].arm_vector, theta_stimato)
        if curr > max:
            max = curr
            best = i
    global curr_answ
    curr_answ = best
    return best

def best_arm():
    max = -100
    best = -1
    for i in range (0, num_arms):
        for j in range (0, num_theta):
            min = 1000000000
            curr = np.matmul(A[i].arm_vector, Th[j].vector)
            if curr < min:
                min = curr
        if min > max:
            best = i
            max = min
    global curr_answ
    curr_answ = best
    return best

def best_value():
    max = -100
    for i in range (0, num_arms):
        for j in range (0, num_theta):
            min = 1000000000
            curr = np.matmul(A[i].arm_vector, Th[j].vector)
            if curr < min:
                min = curr
        if min > max:
            max = min
    return max


def beta(time, delta):
    n = np.abs(np.random.normal(0, 1))
    res = math.sqrt(math.log10(1/delta) + d/2*math.log10(1 + (time*(l**2))/(n*d))) + math.sqrt(n/2)*m
    return res

def best_response():
    min = 1000000000000
    theta_adv = 0
    for i in range (0, num_theta):
        if not i == A[curr_answ].best_theta:
            curr = (norm_2_mat(np.array(theta_stimato) - np.array(Th[i].vector), design_matrix(W)))**2
            if curr < min:
                min = curr
                theta_adv = i
    return theta_adv

def calcola_U (id_arm):
    xi = [0]*d
    q2 = 4*(l**2)*(m**2)
    q1 = 0
    #print("theta_stimato", theta_stimato)
    #print("best_response()", best_response())
    #print("id_arm", id_arm)
    p1 = np.matmul((np.array(theta_stimato) - np.array(Th[best_response()].vector)), np.array(A[id_arm].arm_vector))
    p2 = math.sqrt(2*beta(T, 1/T**3))*norm_2_mat(np.array(A[id_arm].arm_vector), design_matrix(normalize(N)) + np.random.normal(0, 1)*np.identity(d))
    r1 = (p1 + p2)**2
    r2 = (p1 - p2)**2
    if r1 > r2:
        q1 = r1
    else:
        q1 = r2
    if q1 > q2:
        return q2
    else:
        return q1

def calcola_loss():
    loss = 0
    par = 0
    arm_play = arm_to_play()
    best_res = best_response ()
    for i in range (0, num_arms):
        #print("IMPORTANTE: W", W)
        #print("W[i]", W[i])
        #print("calcola_U(i)", calcola_U(i))
        par = W[i]*calcola_U(i)/2
        if math.isnan(par):
            loss += 0.1
        else:
            loss += par
        #print("loss parziale i", loss, i)
    #print("loss", loss)
    #print("lm etc", 4*(l**2)*(m**2))
    L[arm_play] += (4*(l**2)*(m**2) - loss)/1000
    return (4*(l**2)*(m**2) - loss)/1000

In [799]:
len([0,1])

2

In [800]:
ze = arm_y( [0.8705524572652754, 0.0619707940889308, 0.6618039107464511] )
ke = arm_y( [0.29313747095524345, 0.7147227382224571, 0.43880766191059795] )
le = arm_y( [0.3976778652509695, 0.20770310609484777, 0.791678366091227] )

In [801]:
wor = world( [[0.5899011009128065, 0.5657184902992989, 0.6054951466017203], [0.82708485598313, 0.1528251973706528, 0.4138971668624878], [0.4974849256226015, 0.7843065267705409, 0.12423891479137728]] )

In [802]:
create_theta()

In [803]:
ae = arm( [0.9871376736199118, 0.688121853533161, 0.5235809151333978] )
be = arm( [0.03481376451873974, 0.34685413538499243, 0.05591468294799695] )
ce = arm( [0.8484788173613923, 0.9117151239295301, 0.43862231513255734] )
de = arm( [0.6311689207509968, 0.08306431034585382, 0.49042361557796177] )

In [804]:
num_theta

3

In [805]:
Th[2].vector

array([0.83144951, 0.68832904, 0.45909891])

In [806]:
w = [0.25, 0.25, 0.25, 0.25]
V = design_matrix(w)

In [807]:
for i in range (0, num_arms):
    A[i].pull_arm()

In [808]:
for i in range (0, num_arms):
    #print(A[i].best_theta)

0
0
0
0


In [809]:
for i in range(0, num_arms):
    for j in range (0, num_theta):
        #print(np.matmul(A[i].arm_vector, Th[j].vector))
#print(best_arm())
#print(best_value())

1.9228288935043807
1.5974799618787874
1.534784812354001
0.4126172746467014
0.2568690843497489
0.29336603143560747
1.9676442382309933
1.5351935764319555
1.534398315792654
0.9590829887935023
0.9495101599700522
0.8071136101287715
0
1.534784812354001


In [810]:
arm_to_play()

0

In [811]:
for i in range (0, num_arms):
    #print(np.matmul(A[i].arm_vector, Th[theta_vero[i]].vector))

1.5974799618787874
0.2568690843497489
1.5351935764319555
0.9495101599700522


In [812]:
def h():
    return np.dot(W, L)

def mix_loss():
    sum = 0
    for i in range (0, num_arms):
        sum += W[i] * math.exp(-eta * L[i])
    return -1/eta * np.log(sum)

def mixability_gap():
    m_g = h() - mix_loss()
    Mixability_Gap.append(m_g)

def new_eta():
    if t>0:
        sum = 0
        for i in range (0, t):
            sum += Mixability_Gap[i]
        eta = math.log(d)/sum
        
def generate_w():
    sum=0
    for i in range (0, num_arms):
        W[i] = math.exp(-eta * L[i])/num_arms
        sum += math.exp(-eta * L[i])/num_arms
    for i in range (0, num_arms):
        W[i] = W[i]/sum
    return W

In [813]:
W

[0, 0, 0, 0]

In [814]:
t += 1
stima_theta()
best_answer()
curr = arm_to_play()
mixability_gap()
generate_w()
err = calcola_loss()
#print(err)
A[curr].pull_arm()

sum [1.6183     1.12809756 0.85835139]
p [[ 17.09806091  -5.04992666 -22.74967552]
 [ -5.04992666   3.46174575   4.47490195]
 [-22.74967552   4.47490195  34.21426989]]
res [ 2.44576644 -0.42607108 -2.39980781]
theta_stimato [ 2.44576644 -0.42607108 -2.39980781]
best_response() 2
id_arm 0
theta_stimato [ 2.44576644 -0.42607108 -2.39980781]
best_response() 2
id_arm 1
theta_stimato [ 2.44576644 -0.42607108 -2.39980781]
best_response() 2
id_arm 2
theta_stimato [ 2.44576644 -0.42607108 -2.39980781]
best_response() 2
id_arm 3
3.596537820009926


D:\Programmi\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  


0.8065565953745695

In [815]:
t += 1
stima_theta()
best_answer()
curr = arm_to_play()
mixability_gap()
new_eta()
generate_w()
err = calcola_loss()
#print(err)
A[curr].pull_arm()

sum [1.60771793 1.02266699 0.84135544]
p [[ 15.64088418  -4.79607541 -21.31988073]
 [ -4.79607541   3.41752294   4.22582084]
 [-21.31988073   4.22582084  32.81134251]]
res [ 2.30374436 -0.6603312  -2.34874562]
theta_stimato [ 2.30374436 -0.6603312  -2.34874562]
best_response() 2
id_arm 0
theta_stimato [ 2.30374436 -0.6603312  -2.34874562]
best_response() 2
id_arm 1
theta_stimato [ 2.30374436 -0.6603312  -2.34874562]
best_response() 2
id_arm 2
theta_stimato [ 2.30374436 -0.6603312  -2.34874562]
best_response() 2
id_arm 3
3.587118685285068


1.1087287948906928

In [816]:
for i in range (800):
    t += 1
    stima_theta()
    best_answer()
    curr = arm_to_play()
    mixability_gap()
    new_eta()
    generate_w()
    err = calcola_loss()
    #print("err", err)
    A[curr].pull_arm()
    if best_answer() == best_arm():
        sample_correct[i] += 1
    error_reward[i] += best_value() - np.dot(A[best_arm()].arm_vector, np.transpose(stima_theta()))
    error_best_choosen[i] += best_value() - np.dot(A[best_answer()].arm_vector, np.transpose(stima_theta()))

sum [2.81068928 2.31529463 1.46323317]
p [[ 12.0747643   -2.86003868 -17.37257218]
 [ -2.86003868   2.3664539    2.08283783]
 [-17.37257218   2.08283783  28.44209937]]
res [ 1.8964546   0.48803532 -2.38909608]
theta_stimato [ 1.8964546   0.48803532 -2.38909608]
best_response() 2
id_arm 0
theta_stimato [ 1.8964546   0.48803532 -2.38909608]
best_response() 2
id_arm 1
theta_stimato [ 1.8964546   0.48803532 -2.38909608]
best_response() 2
id_arm 2
theta_stimato [ 1.8964546   0.48803532 -2.38909608]
best_response() 2
id_arm 3
err 3.591769244516236
sum [2.81068928 2.31529463 1.46323317]
p [[ 12.07454842  -2.86792358 -17.36809442]
 [ -2.86792358   2.07845617   2.24638915]
 [-17.36809442   2.24638915  28.34922005]]
res [ 1.88414399  0.03838746 -2.1337451 ]
sum [2.81068928 2.31529463 1.46323317]
p [[ 12.07454842  -2.86792358 -17.36809442]
 [ -2.86792358   2.07845617   2.24638915]
 [-17.36809442   2.24638915  28.34922005]]
res [ 1.88414399  0.03838746 -2.1337451 ]
sum [4.10792616 2.4860161  2.471

D:\Programmi\Anaconda3\lib\site-packages\ipykernel_launcher.py:153: RuntimeWarning: invalid value encountered in sqrt


1
id_arm 3
err 3.5984087944586975
sum [17.5738534  12.7511325  10.55528806]
p [[ 5.03311499 -1.36757716 -6.85877901]
 [-1.36757716  0.71382399  1.47305151]
 [-6.85877901  1.47305151 10.04263851]]
res [-1.38332079  0.61694676  4.25084035]
sum [17.5738534  12.7511325  10.55528806]
p [[ 5.03311499 -1.36757716 -6.85877901]
 [-1.36757716  0.71382399  1.47305151]
 [-6.85877901  1.47305151 10.04263851]]
res [-1.38332079  0.61694676  4.25084035]
sum [18.94288384 13.70546723 11.2814261 ]
p [[ 5.03311499 -1.36757716 -6.85877901]
 [-1.36757716  0.71382399  1.47305151]
 [-6.85877901  1.47305151 10.04263851]]
res [-0.77837985  0.49555775  3.55908909]
theta_stimato [-0.77837985  0.49555775  3.55908909]
best_response() 1
id_arm 0
theta_stimato [-0.77837985  0.49555775  3.55908909]
best_response() 1
id_arm 1
theta_stimato [-0.77837985  0.49555775  3.55908909]
best_response() 1
id_arm 2
theta_stimato [-0.77837985  0.49555775  3.55908909]
best_response() 1
id_arm 3
err 3.5942178621292613
sum [18.9428838

best_response() 1
id_arm 0
theta_stimato [-1.62966421  1.21549646  4.06341403]
best_response() 1
id_arm 1
theta_stimato [-1.62966421  1.21549646  4.06341403]
best_response() 1
id_arm 2
theta_stimato [-1.62966421  1.21549646  4.06341403]
best_response() 1
id_arm 3
err 3.590219946564144
sum [27.13608925 20.9090112  15.97418873]
p [[ 3.72843651 -1.04416033 -5.06788519]
 [-1.04416033  0.5252252   1.15306139]
 [-5.06788519  1.15306139  7.35624053]]
res [-1.61252872  1.06673186  4.09676327]
sum [27.13608925 20.9090112  15.97418873]
p [[ 3.72843651 -1.04416033 -5.06788519]
 [-1.04416033  0.5252252   1.15306139]
 [-5.06788519  1.15306139  7.35624053]]
res [-1.61252872  1.06673186  4.09676327]
sum [27.19375869 21.48357948 16.06681212]
p [[ 3.72843651 -1.04416033 -5.06788519]
 [-1.04416033  0.5252252   1.15306139]
 [-5.06788519  1.15306139  7.35624053]]
res [-2.46685795  1.41509391  5.14837354]
theta_stimato [-2.46685795  1.41509391  5.14837354]
best_response() 1
id_arm 0
theta_stimato [-2.46685

sum [32.51985393 25.35023937 19.39833877]
p [[ 2.89213588 -0.78341729 -3.96282214]
 [-0.78341729  0.39932526  0.85867488]
 [-3.96282214  0.85867488  5.80888248]]
res [-2.68014567  1.30324117  5.57988684]
sum [35.00645866 27.08362175 20.71724171]
p [[ 2.89213588 -0.78341729 -3.96282214]
 [-0.78341729  0.39932526  0.85867488]
 [-3.96282214  0.85867488  5.80888248]]
res [-2.0730864   1.17988421  4.87567866]
theta_stimato [-2.0730864   1.17988421  4.87567866]
best_response() 1
id_arm 0
theta_stimato [-2.0730864   1.17988421  4.87567866]
best_response() 1
id_arm 1
theta_stimato [-2.0730864   1.17988421  4.87567866]
best_response() 1
id_arm 2
theta_stimato [-2.0730864   1.17988421  4.87567866]
best_response() 1
id_arm 3
err 3.5987641407440125
sum [35.00645866 27.08362175 20.71724171]
p [[ 2.83723351 -0.7722609  -3.89913363]
 [-0.7722609   0.39705823  0.84573311]
 [-3.89913363  0.84573311  5.73500177]]
res [-2.37341837  1.24091291  5.22407336]
sum [35.00645866 27.08362175 20.71724171]
p [[ 2.

theta_stimato [-3.25578155  1.31390767  6.90508198]
best_response() 1
id_arm 0
theta_stimato [-3.25578155  1.31390767  6.90508198]
best_response() 1
id_arm 1
theta_stimato [-3.25578155  1.31390767  6.90508198]
best_response() 1
id_arm 2
theta_stimato [-3.25578155  1.31390767  6.90508198]
best_response() 1
id_arm 3
err 3.590764686249161
sum [45.02212836 33.88664654 27.01859397]
p [[ 2.40838807 -0.66600146 -3.29045332]
 [-0.66600146  0.33689891  0.73751199]
 [-3.29045332  0.73751199  4.79565894]]
res [-3.04122163  1.35810813  6.42055801]
sum [45.02212836 33.88664654 27.01859397]
p [[ 2.40838807 -0.66600146 -3.29045332]
 [-0.66600146  0.33689891  0.73751199]
 [-3.29045332  0.73751199  4.79565894]]
res [-3.04122163  1.35810813  6.42055801]
sum [46.885771   35.88918467 27.98200665]
p [[ 2.40838807 -0.66600146 -3.29045332]
 [-0.66600146  0.33689891  0.73751199]
 [-3.29045332  0.73751199  4.79565894]]
res [-3.05660469  1.50210073  6.38542339]
theta_stimato [-3.05660469  1.50210073  6.38542339

 [-2.88600701  0.64572824  4.20956137]]
res [-2.27113822  1.3775963   5.01783936]
sum [52.35207871 40.92413283 30.75191613]
p [[ 2.1098092  -0.58130848 -2.88600701]
 [-0.58130848  0.29026302  0.64572824]
 [-2.88600701  0.64572824  4.20956137]]
res [-2.08689372  1.30343559  4.78948037]
theta_stimato [-2.08689372  1.30343559  4.78948037]
best_response() 1
id_arm 0
theta_stimato [-2.08689372  1.30343559  4.78948037]
best_response() 1
id_arm 1
theta_stimato [-2.08689372  1.30343559  4.78948037]
best_response() 1
id_arm 2
theta_stimato [-2.08689372  1.30343559  4.78948037]
best_response() 1
id_arm 3
err 3.597828954048364
sum [52.35207871 40.92413283 30.75191613]
p [[ 2.02999413 -0.54918192 -2.78708146]
 [-0.54918192  0.27733168  0.60590947]
 [-2.78708146  0.60590947  4.08694964]]
res [-1.90847681  1.23162057  4.56834431]
sum [52.35207871 40.92413283 30.75191613]
p [[ 2.02999413 -0.54918192 -2.78708146]
 [-0.54918192  0.27733168  0.60590947]
 [-2.78708146  0.60590947  4.08694964]]
res [-1.90

sum [64.98503529 51.20592013 37.76847098]
p [[ 1.63923298 -0.44321086 -2.2525494 ]
 [-0.44321086  0.22288376  0.49041246]
 [-2.2525494   0.49041246  3.30363162]]
res [-1.24475338  1.13302308  3.50313352]
sum [65.71406676 51.71411925 38.15515156]
p [[ 1.63923298 -0.44321086 -2.2525494 ]
 [-0.44321086  0.22288376  0.49041246]
 [-2.2525494   0.49041246  3.30363162]]
res [-1.14595742  1.11281071  3.38763146]
theta_stimato [-1.14595742  1.11281071  3.38763146]
best_response() 1
id_arm 0
theta_stimato [-1.14595742  1.11281071  3.38763146]
best_response() 1
id_arm 1
theta_stimato [-1.14595742  1.11281071  3.38763146]
best_response() 1
id_arm 2
theta_stimato [-1.14595742  1.11281071  3.38763146]
best_response() 1
id_arm 3
err 3.5985997797606832
sum [65.71406676 51.71411925 38.15515156]
p [[ 1.6218813  -0.43966093 -2.23226361]
 [-0.43966093  0.22215749  0.48626225]
 [-2.23226361  0.48626225  3.27991556]]
res [-1.32861793  1.15018067  3.6011793 ]
sum [65.71406676 51.71411925 38.15515156]
p [[ 1.

sum [74.57383861 58.27325516 43.5758712 ]
p [[ 1.37466277 -0.37153115 -1.89008408]
 [-0.37153115  0.18631239  0.41189553]
 [-1.89008408  0.41189553  2.77231375]]
res [-1.49851039  1.0992317   3.85765468]
sum [75.88831502 59.18956093 44.27307361]
p [[ 1.37466277 -0.37153115 -1.89008408]
 [-0.37153115  0.18631239  0.41189553]
 [-1.89008408  0.41189553  2.77231375]]
res [-1.34975591  1.06875644  3.6834698 ]
theta_stimato [-1.34975591  1.06875644  3.6834698 ]
best_response() 1
id_arm 0
theta_stimato [-1.34975591  1.06875644  3.6834698 ]
best_response() 1
id_arm 1
theta_stimato [-1.34975591  1.06875644  3.6834698 ]
best_response() 1
id_arm 2
theta_stimato [-1.34975591  1.06875644  3.6834698 ]
best_response() 1
id_arm 3
err 3.59630580498706
sum [75.88831502 59.18956093 44.27307361]
p [[ 1.36250015 -0.3690394  -1.8758422 ]
 [-0.3690394   0.18580191  0.4089778 ]
 [-1.8758422   0.4089778   2.75563714]]
res [-1.49473889  1.09845904  3.85323843]
sum [75.88831502 59.18956093 44.27307361]
p [[ 1.36

sum [90.30175726 69.83624474 52.53741303]
p [[ 1.21022579 -0.33043511 -1.66118638]
 [-0.33043511  0.16429754  0.36826514]
 [-1.66118638  0.36826514  2.42938108]]
res [-1.06526681  0.98274983  3.34360304]
sum [90.3074442  69.89290454 52.54654688]
p [[ 1.21022579 -0.33043511 -1.66118638]
 [-0.33043511  0.16429754  0.36826514]
 [-1.66118638  0.36826514  2.42938108]]
res [-1.09227974  0.99354341  3.3772114 ]
theta_stimato [-1.09227974  0.99354341  3.3772114 ]
best_response() 1
id_arm 0
theta_stimato [-1.09227974  0.99354341  3.3772114 ]
best_response() 1
id_arm 1
theta_stimato [-1.09227974  0.99354341  3.3772114 ]
best_response() 1
id_arm 2
theta_stimato [-1.09227974  0.99354341  3.3772114 ]
best_response() 1
id_arm 3
err 3.594842717559426
sum [90.3074442  69.89290454 52.54654688]
p [[ 1.18364224 -0.3198131  -1.62811223]
 [-0.3198131   0.1600533   0.35504968]
 [-1.62811223  0.35504968  2.38823161]]
res [-1.01263695  0.96172047  3.27812316]
sum [90.3074442  69.89290454 52.54654688]
p [[ 1.1

best_response() 1
id_arm 3
err 3.5934104910854554
sum [110.28593563  85.93798729  63.83274099]
p [[ 1.03231684 -0.27931542 -1.42180333]
 [-0.27931542  0.13999144  0.31032421]
 [-1.42180333  0.31032421  2.08809794]]
res [-0.91138043  1.03486506  3.15274304]
sum [110.28593563  85.93798729  63.83274099]
p [[ 1.03231684 -0.27931542 -1.42180333]
 [-0.27931542  0.13999144  0.31032421]
 [-1.42180333  0.31032421  2.08809794]]
res [-0.91138043  1.03486506  3.15274304]
sum [111.16098171  86.0531468   64.51265924]
p [[ 1.03231684 -0.27931542 -1.42180333]
 [-0.27931542  0.13999144  0.31032421]
 [-1.42180333  0.31032421  2.08809794]]
res [-1.00693147  1.01756763  3.36407227]
theta_stimato [-1.00693147  1.01756763  3.36407227]
best_response() 1
id_arm 0
theta_stimato [-1.00693147  1.01756763  3.36407227]
best_response() 1
id_arm 1
theta_stimato [-1.00693147  1.01756763  3.36407227]
best_response() 1
id_arm 2
theta_stimato [-1.00693147  1.01756763  3.36407227]
best_response() 1
id_arm 3
err 3.5937755

theta_stimato [-0.74416377  0.98471447  3.05470094]
best_response() 1
id_arm 0
theta_stimato [-0.74416377  0.98471447  3.05470094]
best_response() 1
id_arm 1
theta_stimato [-0.74416377  0.98471447  3.05470094]
best_response() 1
id_arm 2
theta_stimato [-0.74416377  0.98471447  3.05470094]
best_response() 1
id_arm 3
err 3.5912465689204662
sum [128.18044055  99.27061473  74.23851541]
p [[ 0.92075203 -0.24904219 -1.26830825]
 [-0.24904219  0.124629    0.27692264]
 [-1.26830825  0.27692264  1.86250741]]
res [-0.85749221  1.00798547  3.1877556 ]
sum [128.18044055  99.27061473  74.23851541]
p [[ 0.92075203 -0.24904219 -1.26830825]
 [-0.24904219  0.124629    0.27692264]
 [-1.26830825  0.27692264  1.86250741]]
res [-0.85749221  1.00798547  3.1877556 ]
sum [127.57314276  99.19069196  73.76663986]
p [[ 0.92075203 -0.24904219 -1.26830825]
 [-0.24904219  0.124629    0.27692264]
 [-1.26830825  0.27692264  1.86250741]]
res [-0.79827509  1.01859452  3.05699228]
theta_stimato [-0.79827509  1.01859452  

theta_stimato [-0.89259416  1.05294107  3.24026609]
best_response() 1
id_arm 1
theta_stimato [-0.89259416  1.05294107  3.24026609]
best_response() 1
id_arm 2
theta_stimato [-0.89259416  1.05294107  3.24026609]
best_response() 1
id_arm 3
err 3.596199535949927
sum [137.49621049 106.84465859  79.5787493 ]
p [[ 0.87022104 -0.23683368 -1.19600851]
 [-0.23683368  0.11804071  0.26409018]
 [-1.19600851  0.26409018  1.75084858]]
res [-0.82917949  1.0642522   3.10032671]
sum [137.49621049 106.84465859  79.5787493 ]
p [[ 0.87022104 -0.23683368 -1.19600851]
 [-0.23683368  0.11804071  0.26409018]
 [-1.19600851  0.26409018  1.75084858]]
res [-0.82917949  1.0642522   3.10032671]
sum [138.78691007 108.23155276  80.24597826]
p [[ 0.87022104 -0.23683368 -1.19600851]
 [-0.23683368  0.11804071  0.26409018]
 [-1.19600851  0.26409018  1.75084858]]
res [-0.83246032  1.09848966  3.09112103]
theta_stimato [-0.83246032  1.09848966  3.09112103]
best_response() 1
id_arm 0
theta_stimato [-0.83246032  1.09848966  3

sum [152.8495775  119.84449123  88.09022551]
p [[ 0.79231215 -0.21421658 -1.09154597]
 [-0.21421658  0.10701444  0.23842712]
 [-1.09154597  0.23842712  1.60277152]]
res [-0.72263001  1.08527706  2.92034083]
sum [153.28609003 119.90193799  88.42939946]
p [[ 0.79231215 -0.21421658 -1.09154597]
 [-0.21421658  0.10701444  0.23842712]
 [-1.09154597  0.23842712  1.60277152]]
res [-0.75930583  1.07878474  3.00118254]
theta_stimato [-0.75930583  1.07878474  3.00118254]
best_response() 1
id_arm 0
theta_stimato [-0.75930583  1.07878474  3.00118254]
best_response() 1
id_arm 1
theta_stimato [-0.75930583  1.07878474  3.00118254]
best_response() 1
id_arm 2
theta_stimato [-0.75930583  1.07878474  3.00118254]
best_response() 1
id_arm 3
err 3.5980252461625875
sum [153.28609003 119.90193799  88.42939946]
p [[ 0.78956331 -0.21470317 -1.08548691]
 [-0.21470317  0.10692831  0.23949969]
 [-1.08548691  0.23949969  1.58941599]]
res [-0.70320978  1.08871481  2.8775343 ]
sum [153.28609003 119.90193799  88.42939

res [-0.61813449  1.09609313  2.71989799]
theta_stimato [-0.61813449  1.09609313  2.71989799]
best_response() 1
id_arm 0
theta_stimato [-0.61813449  1.09609313  2.71989799]
best_response() 1
id_arm 1
theta_stimato [-0.61813449  1.09609313  2.71989799]
best_response() 1
id_arm 2
theta_stimato [-0.61813449  1.09609313  2.71989799]
best_response() 1
id_arm 3
err 3.594933505391223
sum [165.61151954 130.62063536  95.28458958]
p [[ 0.72489936 -0.19594938 -0.99874958]
 [-0.19594938  0.09779968  0.21820471]
 [-0.99874958  0.21820471  1.4664371 ]]
res [-0.70879259  1.11472759  2.82645906]
sum [165.61151954 130.62063536  95.28458958]
p [[ 0.72489936 -0.19594938 -0.99874958]
 [-0.19594938  0.09779968  0.21820471]
 [-0.99874958  0.21820471  1.4664371 ]]
res [-0.70879259  1.11472759  2.82645906]
sum [166.14684632 130.69108647  95.70054303]
p [[ 0.72489936 -0.19594938 -0.99874958]
 [-0.19594938  0.09779968  0.21820471]
 [-0.99874958  0.21820471  1.4664371 ]]
res [-0.74997274  1.10748374  2.91714401]

best_response() 1
id_arm 2
theta_stimato [-0.63896612  1.09217121  2.67682594]
best_response() 1
id_arm 3
err 3.59967656569015
sum [173.73002758 136.81583453  99.97983915]
p [[ 0.67936926 -0.18450044 -0.93439415]
 [-0.18450044  0.09150304  0.20602453]
 [-0.93439415  0.20602453  1.36856959]]
res [-0.63631696  1.06409809  2.68446448]
sum [173.73002758 136.81583453  99.97983915]
p [[ 0.67936926 -0.18450044 -0.93439415]
 [-0.18450044  0.09150304  0.20602453]
 [-0.93439415  0.20602453  1.36856959]]
res [-0.63631696  1.06409809  2.68446448]
sum [173.76217642 137.13613767 100.03147368]
p [[ 0.67936926 -0.18450044 -0.93439415]
 [-0.18450044  0.09150304  0.20602453]
 [-0.93439415  0.20602453  1.36856959]]
res [-0.7218191   1.0981133   2.79108054]
theta_stimato [-0.7218191   1.0981133   2.79108054]
best_response() 1
id_arm 0
theta_stimato [-0.7218191   1.0981133   2.79108054]
best_response() 1
id_arm 1
theta_stimato [-0.7218191   1.0981133   2.79108054]
best_response() 1
id_arm 2
theta_stimato [

theta_stimato [-0.65793945  1.0653965   2.76706398]
best_response() 1
id_arm 0
theta_stimato [-0.65793945  1.0653965   2.76706398]
best_response() 1
id_arm 1
theta_stimato [-0.65793945  1.0653965   2.76706398]
best_response() 1
id_arm 2
theta_stimato [-0.65793945  1.0653965   2.76706398]
best_response() 1
id_arm 3
err 3.5997255536263886
sum [188.71223353 148.25887817 108.63479201]
p [[ 0.62919574 -0.17081155 -0.8655399 ]
 [-0.17081155  0.08493918  0.19067649]
 [-0.8655399   0.19067649  1.26793104]]
res [-0.61514172  1.07285895  2.67293967]
sum [188.71223353 148.25887817 108.63479201]
p [[ 0.62919574 -0.17081155 -0.8655399 ]
 [-0.17081155  0.08493918  0.19067649]
 [-0.8655399   0.19067649  1.26793104]]
res [-0.61514172  1.07285895  2.67293967]
sum [190.25806518 149.91991917 109.43391185]
p [[ 0.62919574 -0.17081155 -0.8655399 ]
 [-0.17081155  0.08493918  0.19067649]
 [-0.8655399   0.19067649  1.26793104]]
res [-0.61790612  1.10227387  2.66491101]
theta_stimato [-0.61790612  1.10227387  

theta_stimato [-0.64207344  1.1156728   2.70543817]
best_response() 1
id_arm 2
theta_stimato [-0.64207344  1.1156728   2.70543817]
best_response() 1
id_arm 3
err 3.594325312260589
sum [198.42801994 156.44118812 114.13882646]
p [[ 0.60678616 -0.16466786 -0.83479234]
 [-0.16466786  0.0816384   0.18392735]
 [-0.83479234  0.18392735  1.22293877]]
res [-0.63967854  1.09014257  2.71241623]
sum [198.42801994 156.44118812 114.13882646]
p [[ 0.60678616 -0.16466786 -0.83479234]
 [-0.16466786  0.0816384   0.18392735]
 [-0.83479234  0.18392735  1.22293877]]
res [-0.63967854  1.09014257  2.71241623]
sum [198.43581946 156.51889585 114.15135334]
p [[ 0.60678616 -0.16466786 -0.83479234]
 [-0.16466786  0.0816384   0.18392735]
 [-0.83479234  0.18392735  1.22293877]]
res [-0.65819921  1.09750621  2.73551744]
theta_stimato [-0.65819921  1.09750621  2.73551744]
best_response() 1
id_arm 0
theta_stimato [-0.65819921  1.09750621  2.73551744]
best_response() 1
id_arm 1
theta_stimato [-0.65819921  1.09750621  2

theta_stimato [-0.49277322  1.05135777  2.46021509]
best_response() 1
id_arm 1
theta_stimato [-0.49277322  1.05135777  2.46021509]
best_response() 1
id_arm 2
theta_stimato [-0.49277322  1.05135777  2.46021509]
best_response() 1
id_arm 3
err 3.5963221532906733
sum [205.97027873 162.57290524 118.26339699]
p [[ 0.56994178 -0.15385453 -0.78497416]
 [-0.15385453  0.07650317  0.17155391]
 [-0.78497416  0.17155391  1.15170629]]
res [-0.45522124  1.03643126  2.4133697 ]
sum [205.97027873 162.57290524 118.26339699]
p [[ 0.56994178 -0.15385453 -0.78497416]
 [-0.15385453  0.07650317  0.17155391]
 [-0.78497416  0.17155391  1.15170629]]
res [-0.45522124  1.03643126  2.4133697 ]
sum [206.10550851 162.6671723  118.33512329]
p [[ 0.56994178 -0.15385453 -0.78497416]
 [-0.15385453  0.07650317  0.17155391]
 [-0.78497416  0.17155391  1.15170629]]
res [-0.44895485  1.0351422   2.40599733]
theta_stimato [-0.44895485  1.0351422   2.40599733]
best_response() 1
id_arm 0
theta_stimato [-0.44895485  1.0351422   

theta_stimato [-0.5148246   1.01223537  2.52318744]
best_response() 1
id_arm 1
theta_stimato [-0.5148246   1.01223537  2.52318744]
best_response() 1
id_arm 2
theta_stimato [-0.5148246   1.01223537  2.52318744]
best_response() 1
id_arm 3
err 3.592879723068701
sum [216.18701523 169.77300892 124.28546187]
p [[ 0.53953827 -0.14633608 -0.74245582]
 [-0.14633608  0.07270628  0.16342048]
 [-0.74245582  0.16342048  1.08789786]]
res [-0.47921377  1.0183924   2.44496648]
sum [216.18701523 169.77300892 124.28546187]
p [[ 0.53953827 -0.14633608 -0.74245582]
 [-0.14633608  0.07270628  0.16342048]
 [-0.74245582  0.16342048  1.08789786]]
res [-0.47921377  1.0183924   2.44496648]
sum [216.62932273 170.24828117 124.51411336]
p [[ 0.53953827 -0.14633608 -0.74245582]
 [-0.14633608  0.07270628  0.16342048]
 [-0.74245582  0.16342048  1.08789786]]
res [-0.47988505  1.02558847  2.44299138]
theta_stimato [-0.47988505  1.02558847  2.44299138]
best_response() 1
id_arm 0
theta_stimato [-0.47988505  1.02558847  2

res [-0.32799168  1.03000248  2.20245895]
sum [229.40920455 181.04625973 131.48620664]
p [[ 0.51507341 -0.13966531 -0.70885527]
 [-0.13966531  0.06937581  0.15598807]
 [-0.70885527  0.15598807  1.03873501]]
res [-0.32799168  1.03000248  2.20245895]
sum [229.7074339  181.36671584 131.64037672]
p [[ 0.51507341 -0.13966531 -0.70885527]
 [-0.13966531  0.06937581  0.15598807]
 [-0.70885527  0.15598807  1.03873501]]
res [-0.32842255  1.03463078  2.20118669]
theta_stimato [-0.32842255  1.03463078  2.20118669]
best_response() 1
id_arm 0
theta_stimato [-0.32842255  1.03463078  2.20118669]
best_response() 1
id_arm 1
theta_stimato [-0.32842255  1.03463078  2.20118669]
best_response() 1
id_arm 2
theta_stimato [-0.32842255  1.03463078  2.20118669]
best_response() 1
id_arm 3
err 3.5944616914410012
sum [229.7074339  181.36671584 131.64037672]
p [[ 0.51507192 -0.13964932 -0.70885967]
 [-0.13964932  0.06920403  0.15603529]
 [-0.70885967  0.15603529  1.03872203]]
res [-0.32644285  1.01336518  2.20703232

sum [237.97485444 187.02176071 136.60841175]
p [[ 0.48827995 -0.13179411 -0.67261546]
 [-0.13179411  0.06547798  0.14703985]
 [-0.67261546  0.14703985  0.98688202]]
res [-0.33494738  0.96900157  2.25046933]
sum [237.97485444 187.02176071 136.60841175]
p [[ 0.48827995 -0.13179411 -0.67261546]
 [-0.13179411  0.06547798  0.14703985]
 [-0.67261546  0.14703985  0.98688202]]
res [-0.33494738  0.96900157  2.25046933]
sum [238.54083115 187.4162963  136.90860757]
p [[ 0.48827995 -0.13179411 -0.67261546]
 [-0.13179411  0.06547798  0.14703985]
 [-0.67261546  0.14703985  0.98688202]]
res [-0.31250612  0.96438331  2.22405495]
theta_stimato [-0.31250612  0.96438331  2.22405495]
best_response() 1
id_arm 0
theta_stimato [-0.31250612  0.96438331  2.22405495]
best_response() 1
id_arm 1
theta_stimato [-0.31250612  0.96438331  2.22405495]
best_response() 1
id_arm 2
theta_stimato [-0.31250612  0.96438331  2.22405495]
best_response() 1
id_arm 3
err 3.5928182775038
sum [238.54083115 187.4162963  136.90860757

theta_stimato [-0.09809006  0.92339464  1.92810319]
best_response() 1
id_arm 0
theta_stimato [-0.09809006  0.92339464  1.92810319]
best_response() 1
id_arm 1
theta_stimato [-0.09809006  0.92339464  1.92810319]
best_response() 1
id_arm 2
theta_stimato [-0.09809006  0.92339464  1.92810319]
best_response() 1
id_arm 3
err 3.5928957119374965
sum [253.35334716 198.4539356  145.13808831]
p [[ 0.46579054 -0.12622503 -0.64115544]
 [-0.12622503  0.06253658  0.14106142]
 [-0.64115544  0.14106142  0.93964308]]
res [-0.09633659  0.90448096  1.93331823]
sum [253.35334716 198.4539356  145.13808831]
p [[ 0.46579054 -0.12622503 -0.64115544]
 [-0.12622503  0.06253658  0.14106142]
 [-0.64115544  0.14106142  0.93964308]]
res [-0.09633659  0.90448096  1.93331823]
sum [253.37642268 198.68384001 145.17515009]
p [[ 0.46579054 -0.12622503 -0.64115544]
 [-0.12622503  0.06253658  0.14106142]
 [-0.64115544  0.14106142  0.93964308]]
res [-0.13837029  0.92117368  1.98577872]
theta_stimato [-0.13837029  0.92117368  

sum [268.25661435 209.30916687 153.8181444 ]
p [[ 0.4474432  -0.12123061 -0.61594289]
 [-0.12123061  0.0600568   0.13548911]
 [-0.61594289  0.13548911  0.9027397 ]]
res [-0.08827136  0.89020908  1.98610357]
sum [268.25661435 209.30916687 153.8181444 ]
p [[ 0.4474432  -0.12123061 -0.61594289]
 [-0.12123061  0.0600568   0.13548911]
 [-0.61594289  0.13548911  0.9027397 ]]
res [-0.08827136  0.89020908  1.98610357]
sum [268.21389064 208.88350492 153.74952549]
p [[ 0.4474432  -0.12123061 -0.61594289]
 [-0.12123061  0.0600568   0.13548911]
 [-0.61594289  0.13548911  0.9027397 ]]
res [-0.01351921  0.86052749  1.89280136]
theta_stimato [-0.01351921  0.86052749  1.89280136]
best_response() 1
id_arm 0
theta_stimato [-0.01351921  0.86052749  1.89280136]
best_response() 1
id_arm 1
theta_stimato [-0.01351921  0.86052749  1.89280136]
best_response() 1
id_arm 2
theta_stimato [-0.01351921  0.86052749  1.89280136]
best_response() 1
id_arm 3
err 3.597257291964286
sum [268.21389064 208.88350492 153.749525

theta_stimato [0.02431805 0.869514   1.88390364]
best_response() 1
id_arm 0
theta_stimato [0.02431805 0.869514   1.88390364]
best_response() 1
id_arm 1
theta_stimato [0.02431805 0.869514   1.88390364]
best_response() 1
id_arm 2
theta_stimato [0.02431805 0.869514   1.88390364]
best_response() 1
id_arm 3
err 3.5984868161583066
sum [285.33153283 222.26567951 163.52494269]
p [[ 0.42592626 -0.1150278  -0.58702811]
 [-0.1150278   0.05718117  0.12837429]
 [-0.58702811  0.12837429  0.86171942]]
res [-0.03027844  0.880753    1.94818871]
sum [285.33153283 222.26567951 163.52494269]
p [[ 0.42592626 -0.1150278  -0.58702811]
 [-0.1150278   0.05718117  0.12837429]
 [-0.58702811  0.12837429  0.86171942]]
res [-0.03027844  0.880753    1.94818871]
sum [285.40017882 222.27471359 163.5782812 ]
p [[ 0.42592626 -0.1150278  -0.58702811]
 [-0.1150278   0.05718117  0.12837429]
 [-0.58702811  0.12837429  0.86171942]]
res [-0.03339069  0.88022067  1.95501416]
theta_stimato [-0.03339069  0.88022067  1.95501416]


sum [299.98376376 234.96221261 172.07039592]
p [[ 0.40669958 -0.10976105 -0.5603306 ]
 [-0.10976105  0.0544852   0.12252786]
 [-0.5603306   0.12252786  0.8221567 ]]
res [-0.2027358   0.95884718  2.1681644 ]
sum [299.98376376 234.96221261 172.07039592]
p [[ 0.40669958 -0.10976105 -0.5603306 ]
 [-0.10976105  0.0544852   0.12252786]
 [-0.5603306   0.12252786  0.8221567 ]]
res [-0.2027358   0.95884718  2.1681644 ]
sum [300.76965704 235.51004941 172.48723618]
p [[ 0.40669958 -0.10976105 -0.5603306 ]
 [-0.10976105  0.0544852   0.12252786]
 [-0.5603306   0.12252786  0.8221567 ]]
res [-0.17681283  0.95351025  2.13763763]
theta_stimato [-0.17681283  0.95351025  2.13763763]
best_response() 1
id_arm 0
theta_stimato [-0.17681283  0.95351025  2.13763763]
best_response() 1
id_arm 1
theta_stimato [-0.17681283  0.95351025  2.13763763]
best_response() 1
id_arm 2
theta_stimato [-0.17681283  0.95351025  2.13763763]
best_response() 1
id_arm 3
err 3.5988056608815278
sum [300.76965704 235.51004941 172.48723

theta_stimato [-0.15975362  0.88102567  2.1940116 ]
best_response() 1
id_arm 1
theta_stimato [-0.15975362  0.88102567  2.1940116 ]
best_response() 1
id_arm 2
theta_stimato [-0.15975362  0.88102567  2.1940116 ]
best_response() 1
id_arm 3
err 3.5993864778700346
sum [312.71199757 242.43960996 179.68061753]
p [[ 0.39097632 -0.10587988 -0.5383217 ]
 [-0.10587988  0.05253166  0.11832012]
 [-0.5383217   0.11832012  0.78911332]]
res [-0.13246685  0.88567781  2.13419715]
sum [312.71199757 242.43960996 179.68061753]
p [[ 0.39097632 -0.10587988 -0.5383217 ]
 [-0.10587988  0.05253166  0.11832012]
 [-0.5383217   0.11832012  0.78911332]]
res [-0.13246685  0.88567781  2.13419715]
sum [313.97101113 243.79245659 180.33146635]
p [[ 0.39097632 -0.10587988 -0.5383217 ]
 [-0.10587988  0.05253166  0.11832012]
 [-0.5383217   0.11832012  0.78911332]]
res [-0.13382765  0.9004494   2.13010527]
theta_stimato [-0.13382765  0.9004494   2.13010527]
best_response() 1
id_arm 0
theta_stimato [-0.13382765  0.9004494   

sum [319.69203211 248.53533306 183.58411003]
p [[ 0.37952413 -0.10242274 -0.52291865]
 [-0.10242274  0.0508281   0.11435766]
 [-0.52291865  0.11435766  0.76727019]]
res [-0.12438502  0.88309474  2.10760801]
sum [319.83531723 248.6352154  183.6601089 ]
p [[ 0.37952413 -0.10242274 -0.52291865]
 [-0.10242274  0.0508281   0.11435766]
 [-0.52291865  0.11435766  0.76727019]]
res [-0.11997631  0.88218697  2.10241554]
theta_stimato [-0.11997631  0.88218697  2.10241554]
best_response() 1
id_arm 0
theta_stimato [-0.11997631  0.88218697  2.10241554]
best_response() 1
id_arm 1
theta_stimato [-0.11997631  0.88218697  2.10241554]
best_response() 1
id_arm 2
theta_stimato [-0.11997631  0.88218697  2.10241554]
best_response() 1
id_arm 3
err 3.5989366717197915
sum [319.83531723 248.6352154  183.6601089 ]
p [[ 0.37860797 -0.1022341  -0.52183962]
 [-0.1022341   0.05078926  0.11413548]
 [-0.52183962  0.11413548  0.76599934]]
res [-0.16791814  0.89205839  2.15888037]
sum [319.83531723 248.6352154  183.66010

id_arm 0
theta_stimato [0.02684824 0.819123   1.93897599]
best_response() 1
id_arm 1
theta_stimato [0.02684824 0.819123   1.93897599]
best_response() 1
id_arm 2
theta_stimato [0.02684824 0.819123   1.93897599]
best_response() 1
id_arm 3
err 3.598644301757621
sum [332.08497758 256.89459041 190.64657627]
p [[ 0.36639653 -0.09893303 -0.50501529]
 [-0.09893303  0.04914131  0.11045993]
 [-0.50501529  0.11045993  0.74129631]]
res [-0.02001167  0.82877223  1.99417043]
sum [332.08497758 256.89459041 190.64657627]
p [[ 0.36639653 -0.09893303 -0.50501529]
 [-0.09893303  0.04914131  0.11045993]
 [-0.50501529  0.11045993  0.74129631]]
res [-0.02001167  0.82877223  1.99417043]
sum [333.45675197 257.07512132 191.71245664]
p [[ 0.36639653 -0.09893303 -0.50501529]
 [-0.09893303  0.04914131  0.11045993]
 [-0.50501529  0.11045993  0.74129631]]
res [-0.07354464  0.81966703  2.11147799]
theta_stimato [-0.07354464  0.81966703  2.11147799]
best_response() 1
id_arm 0
theta_stimato [-0.07354464  0.81966703  2

res [0.0177568  0.80768849 1.98872553]
sum [346.88684423 267.5063444  199.22307186]
p [[ 0.35575296 -0.09600419 -0.49018987]
 [-0.09600419  0.04763108  0.10720893]
 [-0.49018987  0.10720893  0.71925345]]
res [0.06715935 0.79751511 1.93053241]
theta_stimato [0.06715935 0.79751511 1.93053241]
best_response() 1
id_arm 0
theta_stimato [0.06715935 0.79751511 1.93053241]
best_response() 1
id_arm 1
theta_stimato [0.06715935 0.79751511 1.93053241]
best_response() 1
id_arm 2
theta_stimato [0.06715935 0.79751511 1.93053241]
best_response() 1
id_arm 3
err 3.592512391976615
sum [346.88684423 267.5063444  199.22307186]
p [[ 0.3549482  -0.09583847 -0.48924191]
 [-0.09583847  0.04759695  0.10701371]
 [-0.48924191  0.10701371  0.71813682]]
res [0.0211854  0.80698245 1.98468685]
sum [346.88684423 267.5063444  199.22307186]
p [[ 0.3549482  -0.09583847 -0.48924191]
 [-0.09583847  0.04759695  0.10701371]
 [-0.48924191  0.10701371  0.71813682]]
res [0.0211854  0.80698245 1.98468685]
sum [346.90076211 267.5

sum [363.58309815 280.74992146 208.55493442]
p [[ 0.34366325 -0.09302165 -0.47326216]
 [-0.09302165  0.04613142  0.10397323]
 [-0.47326216  0.10397323  0.69383538]]
res [0.1331691  0.81442176 1.82314408]
sum [363.87614543 281.06480926 208.70642562]
p [[ 0.34366325 -0.09302165 -0.47326216]
 [-0.09302165  0.04613142  0.10397323]
 [-0.47326216  0.10397323  0.69383538]]
res [0.13289224 0.81743927 1.82230575]
theta_stimato [0.13289224 0.81743927 1.82230575]
best_response() 1
id_arm 0
theta_stimato [0.13289224 0.81743927 1.82230575]
best_response() 1
id_arm 1
theta_stimato [0.13289224 0.81743927 1.82230575]
best_response() 1
id_arm 2
theta_stimato [0.13289224 0.81743927 1.82230575]
best_response() 1
id_arm 3
err 3.592456331867486
sum [363.87614543 281.06480926 208.70642562]
p [[ 0.34366261 -0.09301469 -0.4732641 ]
 [-0.09301469  0.04605556  0.10399431]
 [-0.4732641   0.10399431  0.69382952]]
res [0.13421255 0.80304903 1.82630368]
sum [363.87614543 281.06480926 208.70642562]
p [[ 0.34366261 -

sum [376.19507129 291.50463679 215.27290062]
p [[ 0.33152727 -0.08946338 -0.456832  ]
 [-0.08946338  0.04437478  0.09992157]
 [-0.456832    0.09992157  0.67031296]]
res [0.29638599 0.79017528 1.5698712 ]
sum [376.19507129 291.50463679 215.27290062]
p [[ 0.33152727 -0.08946338 -0.456832  ]
 [-0.08946338  0.04437478  0.09992157]
 [-0.456832    0.09992157  0.67031296]]
res [0.29638599 0.79017528 1.5698712 ]
sum [376.30625142 291.58213913 215.33187091]
p [[ 0.33152727 -0.08946338 -0.456832  ]
 [-0.08946338  0.04437478  0.09992157]
 [-0.456832    0.09992157  0.67031296]]
res [0.2993721  0.78956028 1.56635326]
theta_stimato [0.2993721  0.78956028 1.56635326]
best_response() 1
id_arm 0
theta_stimato [0.2993721  0.78956028 1.56635326]
best_response() 1
id_arm 1
theta_stimato [0.2993721  0.78956028 1.56635326]
best_response() 1
id_arm 2
theta_stimato [0.2993721  0.78956028 1.56635326]
best_response() 1
id_arm 3
err 3.5949525749949247
sum [376.30625142 291.58213913 215.33187091]
p [[ 0.33082858 

best_response() 1
id_arm 3
err 3.598782000145512
sum [386.08338924 297.97353277 220.65017056]
p [[ 0.32146667 -0.08678943 -0.44310914]
 [-0.08678943  0.04308366  0.09693306]
 [-0.44310914  0.09693306  0.65040401]]
res [0.47987941 0.71812784 1.31816556]
sum [386.08338924 297.97353277 220.65017056]
p [[ 0.32146667 -0.08678943 -0.44310914]
 [-0.08678943  0.04308366  0.09693306]
 [-0.44310914  0.09693306  0.65040401]]
res [0.47987941 0.71812784 1.31816556]
sum [386.5435872  298.03409662 221.00774828]
p [[ 0.32146667 -0.08678943 -0.44310914]
 [-0.08678943  0.04308366  0.09693306]
 [-0.44310914  0.09693306  0.65040401]]
res [0.46411545 0.71545793 1.35268827]
theta_stimato [0.46411545 0.71545793 1.35268827]
best_response() 1
id_arm 0
theta_stimato [0.46411545 0.71545793 1.35268827]
best_response() 1
id_arm 1
theta_stimato [0.46411545 0.71545793 1.35268827]
best_response() 1
id_arm 2
theta_stimato [0.46411545 0.71545793 1.35268827]
best_response() 1
id_arm 3
err 3.592809015905088
sum [386.5435

sum [394.24041136 304.71187092 225.05757272]
p [[ 0.31324365 -0.08452721 -0.43165392]
 [-0.08452721  0.04191842  0.09442036]
 [-0.43165392  0.09442036  0.63337281]]
res [0.58987634 0.69901509 1.14093255]
theta_stimato [0.58987634 0.69901509 1.14093255]
best_response() 1
id_arm 0
theta_stimato [0.58987634 0.69901509 1.14093255]
best_response() 1
id_arm 1
theta_stimato [0.58987634 0.69901509 1.14093255]
best_response() 1
id_arm 2
theta_stimato [0.58987634 0.69901509 1.14093255]
best_response() 1
id_arm 3
err 3.599393988109637
sum [394.24041136 304.71187092 225.05757272]
p [[ 0.31262003 -0.08439877 -0.43091915]
 [-0.08439877  0.04189197  0.09426902]
 [-0.43091915  0.09426902  0.63250709]]
res [0.54852352 0.70753259 1.18965539]
sum [394.24041136 304.71187092 225.05757272]
p [[ 0.31262003 -0.08439877 -0.43091915]
 [-0.08439877  0.04189197  0.09426902]
 [-0.43091915  0.09426902  0.63250709]]
res [0.54852352 0.70753259 1.18965539]
sum [394.4985496  304.74584293 225.25814833]
p [[ 0.31262003 -

res [0.39443001 0.77033522 1.36926312]
sum [404.3730371  313.89962513 230.9123023 ]
p [[ 0.30483781 -0.08225791 -0.42007774]
 [-0.08225791  0.04078948  0.09189083]
 [-0.42007774  0.09189083  0.61638859]]
res [0.44634388 0.759642   1.30809407]
theta_stimato [0.44634388 0.759642   1.30809407]
best_response() 1
id_arm 0
theta_stimato [0.44634388 0.759642   1.30809407]
best_response() 1
id_arm 1
theta_stimato [0.44634388 0.759642   1.30809407]
best_response() 1
id_arm 2
theta_stimato [0.44634388 0.759642   1.30809407]
best_response() 1
id_arm 3
err 3.5970966981959713
sum [404.3730371  313.89962513 230.9123023 ]
p [[ 0.30424726 -0.08213627 -0.41938191]
 [-0.08213627  0.04076442  0.0917475 ]
 [-0.41938191  0.0917475   0.61556871]]
res [0.40640119 0.7678694  1.35515773]
sum [404.3730371  313.89962513 230.9123023 ]
p [[ 0.30424726 -0.08213627 -0.41938191]
 [-0.08213627  0.04076442  0.0917475 ]
 [-0.41938191  0.0917475   0.61556871]]
res [0.40640119 0.7678694  1.35515773]
sum [405.20033545 314.

sum [415.24263961 322.67634122 237.20625092]
p [[ 0.29687132 -0.08010728 -0.40910625]
 [-0.08010728  0.03971975  0.08949329]
 [-0.40910625  0.08949329  0.60029148]]
res [0.38234748 0.78103363 1.39189837]
sum [415.24263961 322.67634122 237.20625092]
p [[ 0.29687132 -0.08010728 -0.40910625]
 [-0.08010728  0.03971975  0.08949329]
 [-0.40910625  0.08949329  0.60029148]]
res [0.38234748 0.78103363 1.39189837]
sum [417.95647422 324.56812284 238.6456773 ]
p [[ 0.29687132 -0.08010728 -0.40910625]
 [-0.08010728  0.03971975  0.08949329]
 [-0.40910625  0.08949329  0.60029148]]
res [0.44758334 0.76759582 1.31502882]
theta_stimato [0.44758334 0.76759582 1.31502882]
best_response() 1
id_arm 0
theta_stimato [0.44758334 0.76759582 1.31502882]
best_response() 1
id_arm 1
theta_stimato [0.44758334 0.76759582 1.31502882]
best_response() 1
id_arm 2
theta_stimato [0.44758334 0.76759582 1.31502882]
best_response() 1
id_arm 3
err 3.5953156974798133
sum [417.95647422 324.56812284 238.6456773 ]
p [[ 0.29631128 

err 3.588734298184688
sum [430.51193842 334.74286846 245.67325216]
p [[ 0.29086552 -0.07868283 -0.40063531]
 [-0.07868283  0.03894921  0.08798779]
 [-0.40063531  0.08798779  0.58743928]]
res [0.45718178 0.78031859 1.29311841]
sum [430.51193842 334.74286846 245.67325216]
p [[ 0.29086552 -0.07868283 -0.40063531]
 [-0.07868283  0.03894921  0.08798779]
 [-0.40063531  0.08798779  0.58743928]]
res [0.45718178 0.78031859 1.29311841]
sum [430.58117374 335.43266915 245.78445161]
p [[ 0.29086552 -0.07868283 -0.40063531]
 [-0.07868283  0.03894921  0.08798779]
 [-0.40063531  0.08798779  0.58743928]]
res [0.37849406 0.81152234 1.39139725]
theta_stimato [0.37849406 0.81152234 1.39139725]
best_response() 1
id_arm 0
theta_stimato [0.37849406 0.81152234 1.39139725]
best_response() 1
id_arm 1
theta_stimato [0.37849406 0.81152234 1.39139725]
best_response() 1
id_arm 2
theta_stimato [0.37849406 0.81152234 1.39139725]
best_response() 1
id_arm 3
err 3.596048172843991
sum [430.58117374 335.43266915 245.78445

sum [440.82595773 344.166445   251.92127398]
p [[ 0.28360427 -0.07671754 -0.39064244]
 [-0.07671754  0.0380242   0.08577275]
 [-0.39064244  0.08577275  0.57280466]]
res [0.20538398 0.87555364 1.61645441]
theta_stimato [0.20538398 0.87555364 1.61645441]
best_response() 1
id_arm 0
theta_stimato [0.20538398 0.87555364 1.61645441]
best_response() 1
id_arm 1
theta_stimato [0.20538398 0.87555364 1.61645441]
best_response() 1
id_arm 2
theta_stimato [0.20538398 0.87555364 1.61645441]
best_response() 1
id_arm 3
err 3.592779272668749
sum [440.82595773 344.166445   251.92127398]
p [[ 0.28360385 -0.07671283 -0.39064375]
 [-0.07671283  0.03797269  0.08578711]
 [-0.39064375  0.08578711  0.57280065]]
res [0.20648279 0.86351521 1.6198114 ]
sum [440.82595773 344.166445   251.92127398]
p [[ 0.28360385 -0.07671283 -0.39064375]
 [-0.07671283  0.03797269  0.08578711]
 [-0.39064375  0.08578711  0.57280065]]
res [0.20648279 0.86351521 1.6198114 ]
sum [440.81583382 344.06557911 251.90501388]
p [[ 0.28360385 -

sum [448.40926044 350.7837167  256.06033857]
p [[ 0.27669634 -0.07484354 -0.38113718]
 [-0.07484354  0.03709295  0.08368016]
 [-0.38113718  0.08368016  0.55887768]]
res [0.225188   0.87823525 1.55460342]
sum [448.40926044 350.7837167  256.06033857]
p [[ 0.27669634 -0.07484354 -0.38113718]
 [-0.07484354  0.03709295  0.08368016]
 [-0.38113718  0.08368016  0.55887768]]
res [0.225188   0.87823525 1.55460342]
sum [449.56432635 352.02486856 256.65745152]
p [[ 0.27669634 -0.07484354 -0.38113718]
 [-0.07484354  0.03709295  0.08368016]
 [-0.38113718  0.08368016  0.55887768]]
res [0.22431636 0.88779052 1.55193773]
theta_stimato [0.22431636 0.88779052 1.55193773]
best_response() 1
id_arm 0
theta_stimato [0.22431636 0.88779052 1.55193773]
best_response() 1
id_arm 1
theta_stimato [0.22431636 0.88779052 1.55193773]
best_response() 1
id_arm 2
theta_stimato [0.22431636 0.88779052 1.55193773]
best_response() 1
id_arm 3
err 3.593466721597116
sum [449.56432635 352.02486856 256.65745152]
p [[ 0.27669593 -

theta_stimato [0.24717903 0.85671863 1.58119606]
best_response() 1
id_arm 2
theta_stimato [0.24717903 0.85671863 1.58119606]
best_response() 1
id_arm 3
err 3.5962412928501317
sum [464.46926647 362.37239576 265.31997762]
p [[ 0.27011693 -0.07305892 -0.37208351]
 [-0.07305892  0.03620622  0.08168725]
 [-0.37208351  0.08168725  0.54561186]]
res [0.26528425 0.85977035 1.54157343]
sum [464.46926647 362.37239576 265.31997762]
p [[ 0.27011693 -0.07305892 -0.37208351]
 [-0.07305892  0.03620622  0.08168725]
 [-0.37208351  0.08168725  0.54561186]]
res [0.26528425 0.85977035 1.54157343]
sum [465.28891615 363.25313314 265.74369668]
p [[ 0.27011693 -0.07305892 -0.37208351]
 [-0.07305892  0.03620622  0.08168725]
 [-0.37208351  0.08168725  0.54561186]]
res [0.2646809  0.86638825 1.53972645]
theta_stimato [0.2646809  0.86638825 1.53972645]
best_response() 1
id_arm 0
theta_stimato [0.2646809  0.86638825 1.53972645]
best_response() 1
id_arm 1
theta_stimato [0.2646809  0.86638825 1.53972645]
best_respons

sum [472.42472385 368.3509276  269.73010368]
p [[ 0.2646015  -0.07139622 -0.36466041]
 [-0.07139622  0.03538868  0.07977943]
 [-0.36466041  0.07977943  0.5350807 ]]
res [0.34553292 0.82502572 1.43960451]
sum [472.42472385 368.3509276  269.73010368]
p [[ 0.2646015  -0.07139622 -0.36466041]
 [-0.07139622  0.03538868  0.07977943]
 [-0.36466041  0.07977943  0.5350807 ]]
res [0.34553292 0.82502572 1.43960451]
sum [474.94136228 370.10524612 271.06493659]
p [[ 0.2646015  -0.07139622 -0.36466041]
 [-0.07139622  0.03538868  0.07977943]
 [-0.36466041  0.07977943  0.5350807 ]]
res [0.39942677 0.81392247 1.37608796]
theta_stimato [0.39942677 0.81392247 1.37608796]
best_response() 1
id_arm 0
theta_stimato [0.39942677 0.81392247 1.37608796]
best_response() 1
id_arm 1
theta_stimato [0.39942677 0.81392247 1.37608796]
best_response() 1
id_arm 2
theta_stimato [0.39942677 0.81392247 1.37608796]
best_response() 1
id_arm 3
err 3.592980765403788
sum [474.94136228 370.10524612 271.06493659]
p [[ 0.26415676 -

sum [480.59831763 374.40940856 274.53044459]
p [[ 0.26012424 -0.07021523 -0.35857909]
 [-0.07021523  0.03482757  0.07845654]
 [-0.35857909  0.07845654  0.52630479]]
res [0.28515029 0.83315664 1.52904744]
sum [480.59831763 374.40940856 274.53044459]
p [[ 0.26012424 -0.07021523 -0.35857909]
 [-0.07021523  0.03482757  0.07845654]
 [-0.35857909  0.07845654  0.52630479]]
res [0.28515029 0.83315664 1.52904744]
sum [481.54258445 374.53367779 275.26414793]
p [[ 0.26012424 -0.07021523 -0.35857909]
 [-0.07021523  0.03482757  0.07845654]
 [-0.35857909  0.07845654  0.52630479]]
res [0.2589607  0.82874655 1.58635442]
theta_stimato [0.2589607  0.82874655 1.58635442]
best_response() 1
id_arm 0
theta_stimato [0.2589607  0.82874655 1.58635442]
best_response() 1
id_arm 1
theta_stimato [0.2589607  0.82874655 1.58635442]
best_response() 1
id_arm 2
theta_stimato [0.2589607  0.82874655 1.58635442]
best_response() 1
id_arm 3
err 3.595523517860423
sum [481.54258445 374.53367779 275.26414793]
p [[ 0.25982007 -

sum [493.7307915  384.27760055 282.05553499]
p [[ 0.25591749 -0.06920452 -0.35254425]
 [-0.06920452  0.03425146  0.07739854]
 [-0.35254425  0.07739854  0.51697562]]
res [0.32353991 0.82435197 1.49640972]
sum [493.7307915  384.27760055 282.05553499]
p [[ 0.25591749 -0.06920452 -0.35254425]
 [-0.06920452  0.03425146  0.07739854]
 [-0.35254425  0.07739854  0.51697562]]
res [0.32353991 0.82435197 1.49640972]
sum [493.69759079 383.94681757 282.00221106]
p [[ 0.25591749 -0.06920452 -0.35254425]
 [-0.06920452  0.03425146  0.07739854]
 [-0.35254425  0.07739854  0.51697562]]
res [0.35673399 0.81119262 1.45494515]
theta_stimato [0.35673399 0.81119262 1.45494515]
best_response() 1
id_arm 0
theta_stimato [0.35673399 0.81119262 1.45494515]
best_response() 1
id_arm 1
theta_stimato [0.35673399 0.81119262 1.45494515]
best_response() 1
id_arm 2
theta_stimato [0.35673399 0.81119262 1.45494515]
best_response() 1
id_arm 3
err 3.596322211507398
sum [493.69759079 383.94681757 282.00221106]
p [[ 0.25471321 -

sum [505.0241469  394.16737685 287.7414515 ]
p [[ 0.2502791  -0.06767595 -0.34478423]
 [-0.06767595  0.033494    0.07569056]
 [-0.34478423  0.07569056  0.50560423]]
res [0.51262152 0.80356244 1.19368203]
sum [505.0241469  394.16737685 287.7414515 ]
p [[ 0.2502791  -0.06767595 -0.34478423]
 [-0.06767595  0.033494    0.07569056]
 [-0.34478423  0.07569056  0.50560423]]
res [0.51262152 0.80356244 1.19368203]
sum [505.0262432  394.1882626  287.74481839]
p [[ 0.2502791  -0.06767595 -0.34478423]
 [-0.06767595  0.033494    0.07569056]
 [-0.34478423  0.07569056  0.50560423]]
res [0.51057187 0.80437496 1.19624243]
theta_stimato [0.51057187 0.80437496 1.19624243]
best_response() 1
id_arm 0
theta_stimato [0.51057187 0.80437496 1.19624243]
best_response() 1
id_arm 1
theta_stimato [0.51057187 0.80437496 1.19624243]
best_response() 1
id_arm 2
theta_stimato [0.51057187 0.80437496 1.19624243]
best_response() 1
id_arm 3
err 3.598726719642798
sum [505.0262432  394.1882626  287.74481839]
p [[ 0.24912721 -

sum [514.38172426 402.16021314 293.08551622]
p [[ 0.24488412 -0.06621693 -0.33735749]
 [-0.06621693  0.03280766  0.07404561]
 [-0.33735749  0.07404561  0.49472532]]
res [0.45950423 0.83484808 1.24449266]
sum [514.38172426 402.16021314 293.08551622]
p [[ 0.24488412 -0.06621693 -0.33735749]
 [-0.06621693  0.03280766  0.07404561]
 [-0.33735749  0.07404561  0.49472532]]
res [0.45950423 0.83484808 1.24449266]
sum [516.76330761 404.71929359 294.31667908]
p [[ 0.24488412 -0.06621693 -0.33735749]
 [-0.06621693  0.03280766  0.07404561]
 [-0.33735749  0.07404561  0.49472532]]
res [0.4579197  0.85226656 1.23962377]
theta_stimato [0.4579197  0.85226656 1.23962377]
best_response() 1
id_arm 0
theta_stimato [0.4579197  0.85226656 1.23962377]
best_response() 1
id_arm 1
theta_stimato [0.4579197  0.85226656 1.23962377]
best_response() 1
id_arm 2
theta_stimato [0.4579197  0.85226656 1.23962377]
best_response() 1
id_arm 3
err 3.597483790968355
sum [516.76330761 404.71929359 294.31667908]
p [[ 0.2448838  -

best_response() 1
id_arm 1
theta_stimato [0.51783049 0.83549188 1.14940097]
best_response() 1
id_arm 2
theta_stimato [0.51783049 0.83549188 1.14940097]
best_response() 1
id_arm 3
err 3.5975494750228947
sum [524.5350684  411.26875833 298.51152068]
p [[ 0.23997565 -0.0647726  -0.33081176]
 [-0.0647726   0.03211938  0.07238563]
 [-0.33081176  0.07238563  0.48554188]]
res [0.48557341 0.8421383  1.18742275]
sum [524.5350684  411.26875833 298.51152068]
p [[ 0.23997565 -0.0647726  -0.33081176]
 [-0.0647726   0.03211938  0.07238563]
 [-0.33081176  0.07238563  0.48554188]]
res [0.48557341 0.8421383  1.18742275]
sum [525.46723976 411.39143574 299.23582574]
p [[ 0.23997565 -0.0647726  -0.33081176]
 [-0.0647726   0.03211938  0.07238563]
 [-0.33081176  0.07238563  0.48554188]]
res [0.46171707 0.83812873 1.23961003]
theta_stimato [0.46171707 0.83812873 1.23961003]
best_response() 1
id_arm 0
theta_stimato [0.46171707 0.83812873 1.23961003]
best_response() 1
id_arm 1
theta_stimato [0.46171707 0.838128

sum [537.66970564 420.16922842 306.41564936]
p [[ 0.23639064 -0.06391152 -0.32566839]
 [-0.06391152  0.03162877  0.07148398]
 [-0.32566839  0.07148398  0.47759069]]
res [0.45654079 0.829956   1.27460397]
sum [537.66970564 420.16922842 306.41564936]
p [[ 0.23639064 -0.06391152 -0.32566839]
 [-0.06391152  0.03162877  0.07148398]
 [-0.32566839  0.07148398  0.47759069]]
res [0.45654079 0.829956   1.27460397]
sum [537.63964355 419.86971588 306.36736639]
p [[ 0.23639064 -0.06391152 -0.32566839]
 [-0.06391152  0.03162877  0.07148398]
 [-0.32566839  0.07148398  0.47759069]]
res [0.48430093 0.81895264 1.23992439]
theta_stimato [0.48430093 0.81895264 1.23992439]
best_response() 1
id_arm 0
theta_stimato [0.48430093 0.81895264 1.23992439]
best_response() 1
id_arm 1
theta_stimato [0.48430093 0.81895264 1.23992439]
best_response() 1
id_arm 2
theta_stimato [0.48430093 0.81895264 1.23992439]
best_response() 1
id_arm 3
err 3.5993678604381913
sum [537.63964355 419.86971588 306.36736639]
p [[ 0.23536285 

theta_stimato [0.5532686  0.81576384 1.13881634]
best_response() 1
id_arm 2
theta_stimato [0.5532686  0.81576384 1.13881634]
best_response() 1
id_arm 3
err 3.5991986368603994
sum [547.78759437 428.34112208 311.87065558]
p [[ 0.23181395 -0.06256811 -0.31956354]
 [-0.06256811  0.03102286  0.06992615]
 [-0.31956354  0.06992615  0.46902967]]
res [0.52181648 0.82224467 1.17589104]
sum [547.78759437 428.34112208 311.87065558]
p [[ 0.23181395 -0.06256811 -0.31956354]
 [-0.06256811  0.03102286  0.06992615]
 [-0.31956354  0.06992615  0.46902967]]
res [0.52181648 0.82224467 1.17589104]
sum [548.4717868  428.43116449 312.40227891]
p [[ 0.23181395 -0.06256811 -0.31956354]
 [-0.06256811  0.03102286  0.06992615]
 [-0.31956354  0.06992615  0.46902967]]
res [0.5049006  0.81940378 1.21289151]
theta_stimato [0.5049006  0.81940378 1.21289151]
best_response() 1
id_arm 0
theta_stimato [0.5049006  0.81940378 1.21289151]
best_response() 1
id_arm 1
theta_stimato [0.5049006  0.81940378 1.21289151]
best_respons

sum [555.69824251 432.92783057 316.46104952]
p [[ 0.22846714 -0.06176731 -0.3147605 ]
 [-0.06176731  0.0305983   0.06907501]
 [-0.3147605   0.06907501  0.46160847]]
res [0.60856538 0.78241905 1.07373618]
sum [555.69824251 432.92783057 316.46104952]
p [[ 0.22846714 -0.06176731 -0.3147605 ]
 [-0.06176731  0.0305983   0.06907501]
 [-0.3147605   0.06907501  0.46160847]]
res [0.60856538 0.78241905 1.07373618]
sum [556.84328786 434.15821505 317.05298232]
p [[ 0.22846714 -0.06176731 -0.3147605 ]
 [-0.06176731  0.0305983   0.06907501]
 [-0.3147605   0.06907501  0.46160847]]
res [0.60785602 0.79022811 1.07155114]
theta_stimato [0.60785602 0.79022811 1.07155114]
best_response() 1
id_arm 0
theta_stimato [0.60785602 0.79022811 1.07155114]
best_response() 1
id_arm 1
theta_stimato [0.60785602 0.79022811 1.07155114]
best_response() 1
id_arm 2
theta_stimato [0.60785602 0.79022811 1.07155114]
best_response() 1
id_arm 3
err 3.592057391526337
sum [556.84328786 434.15821505 317.05298232]
p [[ 0.22846687 -

id_arm 0
theta_stimato [0.62247803 0.76796908 1.05108098]
best_response() 1
id_arm 1
theta_stimato [0.62247803 0.76796908 1.05108098]
best_response() 1
id_arm 2
theta_stimato [0.62247803 0.76796908 1.05108098]
best_response() 1
id_arm 3
err 3.599415107555935
sum [563.31550638 438.87738437 320.68984415]
p [[ 0.22396282 -0.06054673 -0.30856008]
 [-0.06054673  0.02999237  0.06771139]
 [-0.30856008  0.06771139  0.45252096]]
res [0.63705651 0.77041566 1.01919641]
sum [563.31550638 438.87738437 320.68984415]
p [[ 0.22396282 -0.06054673 -0.30856008]
 [-0.06054673  0.02999237  0.06771139]
 [-0.30856008  0.06771139  0.45252096]]
res [0.63705651 0.77041566 1.01919641]
sum [563.84515825 439.44651069 320.96364843]
p [[ 0.22396282 -0.06054673 -0.30856008]
 [-0.06054673  0.02999237  0.06771139]
 [-0.30856008  0.06771139  0.45252096]]
res [0.63673503 0.77395608 1.0182055 ]
theta_stimato [0.63673503 0.77395608 1.0182055 ]
best_response() 1
id_arm 0
theta_stimato [0.63673503 0.77395608 1.0182055 ]
best

theta_stimato [0.61373446 0.75673077 1.06715224]
best_response() 1
id_arm 1
theta_stimato [0.61373446 0.75673077 1.06715224]
best_response() 1
id_arm 2
theta_stimato [0.61373446 0.75673077 1.06715224]
best_response() 1
id_arm 3
err 3.5924427558710126
sum [570.36897847 443.94572322 324.90017258]
p [[ 0.21985038 -0.05933693 -0.30307534]
 [-0.05933693  0.0294161   0.0663207 ]
 [-0.30307534  0.0663207   0.44482559]]
res [0.58422969 0.7628107  1.10193382]
sum [570.36897847 443.94572322 324.90017258]
p [[ 0.21985038 -0.05933693 -0.30307534]
 [-0.05933693  0.0294161   0.0663207 ]
 [-0.30307534  0.0663207   0.44482559]]
res [0.58422969 0.7628107  1.10193382]
sum [571.16744294 444.05080428 325.52058625]
p [[ 0.21985038 -0.05933693 -0.30307534]
 [-0.05933693  0.0294161   0.0663207 ]
 [-0.30307534  0.0663207   0.44482559]]
res [0.56550514 0.75966961 1.14288387]
theta_stimato [0.56550514 0.75966961 1.14288387]
best_response() 1
id_arm 0
theta_stimato [0.56550514 0.75966961 1.14288387]
best_respons

id_arm 2
theta_stimato [0.64634257 0.74196849 1.02591622]
best_response() 1
id_arm 3
err 3.5936817988199476
sum [580.94334084 451.75445357 330.89273711]
p [[ 0.21567636 -0.05820965 -0.29732259]
 [-0.05820965  0.02885565  0.06506269]
 [-0.29732259  0.06506269  0.43638088]]
res [0.61739077 0.74793459 1.06004675]
sum [580.94334084 451.75445357 330.89273711]
p [[ 0.21567636 -0.05820965 -0.29732259]
 [-0.05820965  0.02885565  0.06506269]
 [-0.29732259  0.06506269  0.43638088]]
res [0.61739077 0.74793459 1.06004675]
sum [582.95531629 452.01923745 332.45605913]
p [[ 0.21567636 -0.05820965 -0.29732259]
 [-0.05820965  0.02885565  0.06506269]
 [-0.29732259  0.06506269  0.43638088]]
res [0.57110238 0.74017266 1.16127239]
theta_stimato [0.57110238 0.74017266 1.16127239]
best_response() 1
id_arm 0
theta_stimato [0.57110238 0.74017266 1.16127239]
best_response() 1
id_arm 1
theta_stimato [0.57110238 0.74017266 1.16127239]
best_response() 1
id_arm 2
theta_stimato [0.57110238 0.74017266 1.16127239]
bes

theta_stimato [0.63544866 0.72582721 1.06350168]
best_response() 1
id_arm 0
theta_stimato [0.63544866 0.72582721 1.06350168]
best_response() 1
id_arm 1
theta_stimato [0.63544866 0.72582721 1.06350168]
best_response() 1
id_arm 2
theta_stimato [0.63544866 0.72582721 1.06350168]
best_response() 1
id_arm 3
err 3.5975632227574432
sum [591.71717152 458.88465188 337.27475101]
p [[ 0.21194304 -0.05718316 -0.29212034]
 [-0.05718316  0.02832827  0.0639208 ]
 [-0.29212034  0.0639208   0.42864714]]
res [0.64504547 0.72202405 1.05151162]
sum [591.71717152 458.88465188 337.27475101]
p [[ 0.21194304 -0.05718316 -0.29212034]
 [-0.05718316  0.02832827  0.0639208 ]
 [-0.29212034  0.0639208   0.42864714]]
res [0.64504547 0.72202405 1.05151162]
sum [592.93587485 459.73419537 337.92115507]
p [[ 0.21194304 -0.05718316 -0.29212034]
 [-0.05718316  0.02832827  0.0639208 ]
 [-0.29212034  0.0639208   0.42864714]]
res [0.6659338  0.71771951 1.02688634]
theta_stimato [0.6659338  0.71771951 1.02688634]
best_respons

err 3.5992334549807645
sum [601.6814156 466.714754  342.7664829]
p [[ 0.20886409 -0.05645611 -0.28777441]
 [-0.05645611  0.02796204  0.063141  ]
 [-0.28777441  0.063141    0.42205525]]
res [0.68132318 0.72432438 0.98671266]
sum [601.6814156 466.714754  342.7664829]
p [[ 0.20886409 -0.05645611 -0.28777441]
 [-0.05645611  0.02796204  0.063141  ]
 [-0.28777441  0.063141    0.42205525]]
res [0.68132318 0.72432438 0.98671266]
sum [603.27789063 468.43021277 343.5917829 ]
p [[ 0.20886409 -0.05645611 -0.28777441]
 [-0.05645611  0.02796204  0.063141  ]
 [-0.28777441  0.063141    0.42205525]]
res [0.68042115 0.73427161 0.98392597]
theta_stimato [0.68042115 0.73427161 0.98392597]
best_response() 1
id_arm 0
theta_stimato [0.68042115 0.73427161 0.98392597]
best_response() 1
id_arm 1
theta_stimato [0.68042115 0.73427161 0.98392597]
best_response() 1
id_arm 2
theta_stimato [0.68042115 0.73427161 0.98392597]
best_response() 1
id_arm 3
err 3.594558024220863
sum [603.27789063 468.43021277 343.5917829 ]


best_response() 1
id_arm 1
theta_stimato [0.7078021  0.72889136 0.93722926]
best_response() 1
id_arm 2
theta_stimato [0.7078021  0.72889136 0.93722926]
best_response() 1
id_arm 3
err 3.5972347701519056
sum [611.01848858 475.12218166 347.8061823 ]
p [[ 0.20528315 -0.05540286 -0.28299816]
 [-0.05540286  0.02746049  0.0619301 ]
 [-0.28299816  0.0619301   0.41535364]]
res [0.68016071 0.73458771 0.96981689]
sum [611.01848858 475.12218166 347.8061823 ]
p [[ 0.20528315 -0.05540286 -0.28299816]
 [-0.05540286  0.02746049  0.0619301 ]
 [-0.28299816  0.0619301   0.41535364]]
res [0.68016071 0.73458771 0.96981689]
sum [611.53298092 475.18989087 348.20594721]
p [[ 0.20528315 -0.05540286 -0.28299816]
 [-0.05540286  0.02746049  0.0619301 ]
 [-0.28299816  0.0619301   0.41535364]]
res [0.6688933  0.73270017 0.99445356]
theta_stimato [0.6688933  0.73270017 0.99445356]
best_response() 1
id_arm 0
theta_stimato [0.6688933  0.73270017 0.99445356]
best_response() 1
id_arm 1
theta_stimato [0.6688933  0.732700

best_response() 1
id_arm 0
theta_stimato [0.74330786 0.73272749 0.87452305]
best_response() 1
id_arm 1
theta_stimato [0.74330786 0.73272749 0.87452305]
best_response() 1
id_arm 2
theta_stimato [0.74330786 0.73272749 0.87452305]
best_response() 1
id_arm 3
err 3.5921924611165754
sum [621.53624988 483.46262741 353.59461498]
p [[ 0.20265381 -0.05477164 -0.2792253 ]
 [-0.05477164  0.02710112  0.06126878]
 [-0.2792253   0.06126878  0.40952097]]
res [0.74408696 0.72413128 0.87693218]
sum [621.53624988 483.46262741 353.59461498]
p [[ 0.20265381 -0.05477164 -0.2792253 ]
 [-0.05477164  0.02710112  0.06126878]
 [-0.2792253   0.06126878  0.40952097]]
res [0.74408696 0.72413128 0.87693218]
sum [621.51379822 483.23893852 353.55855517]
p [[ 0.20265381 -0.05477164 -0.2792253 ]
 [-0.05477164  0.02710112  0.06126878]
 [-0.2792253   0.06126878  0.40952097]]
res [0.76185766 0.71708943 0.85472886]
theta_stimato [0.76185766 0.71708943 0.85472886]
best_response() 1
id_arm 0
theta_stimato [0.76185766 0.717089

sum [624.54112476 486.59879204 355.11480037]
p [[ 0.1995339  -0.05383413 -0.27502376]
 [-0.05383413  0.02666575  0.06018233]
 [-0.27502376  0.06018233  0.40356185]]
res [0.75649384 0.72553046 0.83178676]
sum [626.72603955 488.12186999 356.27368602]
p [[ 0.1995339  -0.05383413 -0.27502376]
 [-0.05383413  0.02666575  0.06018233]
 [-0.27502376  0.06018233  0.40356185]]
res [0.79174373 0.71826593 0.7902277 ]
theta_stimato [0.79174373 0.71826593 0.7902277 ]
best_response() 1
id_arm 0
theta_stimato [0.79174373 0.71826593 0.7902277 ]
best_response() 1
id_arm 1
theta_stimato [0.79174373 0.71826593 0.7902277 ]
best_response() 1
id_arm 2
theta_stimato [0.79174373 0.71826593 0.7902277 ]
best_response() 1
id_arm 3
err 3.592554838414167
sum [626.72603955 488.12186999 356.27368602]
p [[ 0.19928118 -0.05378205 -0.27472582]
 [-0.05378205  0.02665502  0.06012093]
 [-0.27472582  0.06012093  0.40321058]]
res [0.76493347 0.72379116 0.82183657]
sum [626.72603955 488.12186999 356.27368602]
p [[ 0.19928118 -

sum [632.06340881 491.67152873 359.18822951]
p [[ 0.19697753 -0.05315997 -0.27155073]
 [-0.05315997  0.0263459   0.05942652]
 [-0.27155073  0.05942652  0.39854986]]
res [0.82722166 0.6983639  0.73546752]
theta_stimato [0.82722166 0.6983639  0.73546752]
best_response() 1
id_arm 0
theta_stimato [0.82722166 0.6983639  0.73546752]
best_response() 1
id_arm 1
theta_stimato [0.82722166 0.6983639  0.73546752]
best_response() 1
id_arm 2
theta_stimato [0.82722166 0.6983639  0.73546752]
best_response() 1
id_arm 3
err 3.599105047513083
sum [632.06340881 491.67152873 359.18822951]
p [[ 0.19680258 -0.05318926 -0.27116822]
 [-0.05318926  0.026341    0.05949054]
 [-0.27116822  0.05949054  0.39771359]]
res [0.8396308  0.70044107 0.70833746]
sum [632.06340881 491.67152873 359.18822951]
p [[ 0.19680258 -0.05318926 -0.27116822]
 [-0.05318926  0.026341    0.05949054]
 [-0.27116822  0.05949054  0.39771359]]
res [0.8396308  0.70044107 0.70833746]
sum [633.28706577 492.98638366 359.8208007 ]
p [[ 0.19680258 -

p [[ 0.19455533 -0.05257855 -0.26807496]
 [-0.05257855  0.02601495  0.0588173 ]
 [-0.26807496  0.0588173   0.39317646]]
res [0.91257943 0.6725662  0.62820658]
sum [643.30145474 499.78096868 365.44775424]
p [[ 0.19455533 -0.05257855 -0.26807496]
 [-0.05257855  0.02601495  0.0588173 ]
 [-0.26807496  0.0588173   0.39317646]]
res [0.91257943 0.6725662  0.62820658]
sum [643.26048818 499.37281342 365.3819575 ]
p [[ 0.19455533 -0.05257855 -0.26807496]
 [-0.05257855  0.02601495  0.0588173 ]
 [-0.26807496  0.0588173   0.39317646]]
res [0.94370784 0.66023204 0.58931237]
theta_stimato [0.94370784 0.66023204 0.58931237]
best_response() 1
id_arm 0
theta_stimato [0.94370784 0.66023204 0.58931237]
best_response() 1
id_arm 1
theta_stimato [0.94370784 0.66023204 0.58931237]
best_response() 1
id_arm 2
theta_stimato [0.94370784 0.66023204 0.58931237]
best_response() 1
id_arm 3
err 3.597470167536996
sum [643.26048818 499.37281342 365.3819575 ]
p [[ 0.19385874 -0.05230253 -0.26720458]
 [-0.05230253  0.0259

best_response() 1
id_arm 0
theta_stimato [0.88834504 0.6855909  0.6468988 ]
best_response() 1
id_arm 1
theta_stimato [0.88834504 0.6855909  0.6468988 ]
best_response() 1
id_arm 2
theta_stimato [0.88834504 0.6855909  0.6468988 ]
best_response() 1
id_arm 3
err 3.5911385383213883
sum [651.43162964 506.36033978 370.08744679]
p [[ 0.19127937 -0.05169151 -0.26356427]
 [-0.05169151  0.02557564  0.0578257 ]
 [-0.26356427  0.0578257   0.38656434]]
res [0.88907093 0.67757376 0.64914722]
sum [651.43162964 506.36033978 370.08744679]
p [[ 0.19127937 -0.05169151 -0.26356427]
 [-0.05169151  0.02557564  0.0578257 ]
 [-0.26356427  0.0578257   0.38656434]]
res [0.88907093 0.67757376 0.64914722]
sum [651.48498207 506.89189713 370.17313658]
p [[ 0.19127937 -0.05169151 -0.26356427]
 [-0.05169151  0.02557564  0.0578257 ]
 [-0.26356427  0.0578257   0.38656434]]
res [0.84921438 0.69336589 0.69894772]
theta_stimato [0.84921438 0.69336589 0.69894772]
best_response() 1
id_arm 0
theta_stimato [0.84921438 0.693365

theta_stimato [0.79017428 0.68394683 0.81515596]
best_response() 1
id_arm 0
theta_stimato [0.79017428 0.68394683 0.81515596]
best_response() 1
id_arm 1
theta_stimato [0.79017428 0.68394683 0.81515596]
best_response() 1
id_arm 2
theta_stimato [0.79017428 0.68394683 0.81515596]
best_response() 1
id_arm 3
err 3.594756378061231
sum [660.77961625 512.47161095 375.94739486]
p [[ 0.18811208 -0.05083595 -0.2592023 ]
 [-0.05083595  0.0251735   0.05686066]
 [-0.2592023   0.05686066  0.38017271]]
res [0.80222186 0.68596183 0.78881948]
sum [660.77961625 512.47161095 375.94739486]
p [[ 0.18811208 -0.05083595 -0.2592023 ]
 [-0.05083595  0.0251735   0.05686066]
 [-0.2592023   0.05686066  0.38017271]]
res [0.80222186 0.68596183 0.78881948]
sum [660.42339252 512.0888382  375.76324451]
p [[ 0.18811208 -0.05083595 -0.2592023 ]
 [-0.05083595  0.0251735   0.05686066]
 [-0.2592023   0.05686066  0.38017271]]
res [0.80240268 0.68396416 0.78937983]
theta_stimato [0.80240268 0.68396416 0.78937983]
best_response

sum [667.58475837 517.28442589 379.861999  ]
p [[ 0.18542075 -0.05002536 -0.25557845]
 [-0.05002536  0.02477552  0.05592988]
 [-0.25557845  0.05592988  0.37503009]]
res [0.8221812  0.66546047 0.77105792]
theta_stimato [0.8221812  0.66546047 0.77105792]
best_response() 1
id_arm 0
theta_stimato [0.8221812  0.66546047 0.77105792]
best_response() 1
id_arm 1
theta_stimato [0.8221812  0.66546047 0.77105792]
best_response() 1
id_arm 2
theta_stimato [0.8221812  0.66546047 0.77105792]
best_response() 1
id_arm 3
err 3.598044682924872
sum [667.58475837 517.28442589 379.861999  ]
p [[ 0.18520255 -0.04998039 -0.25532119]
 [-0.04998039  0.02476626  0.05587686]
 [-0.25532119  0.05587686  0.37472676]]
res [0.79750681 0.67054588 0.80015095]
sum [667.58475837 517.28442589 379.861999  ]
p [[ 0.18520255 -0.04998039 -0.25532119]
 [-0.04998039  0.02476626  0.05587686]
 [-0.25532119  0.05587686  0.37472676]]
res [0.79750681 0.67054588 0.80015095]
sum [668.24976641 517.37194356 380.37871591]
p [[ 0.18520255 -

theta_stimato [0.80291716 0.68038299 0.77681945]
best_response() 1
id_arm 0
theta_stimato [0.80291716 0.68038299 0.77681945]
best_response() 1
id_arm 1
theta_stimato [0.80291716 0.68038299 0.77681945]
best_response() 1
id_arm 2
theta_stimato [0.80291716 0.68038299 0.77681945]
best_response() 1
id_arm 3
err 3.5912087604850673
sum [675.1522177  523.60018979 384.10540598]
p [[ 0.18305964 -0.0494661  -0.25224602]
 [-0.0494661   0.02447358  0.05533788]
 [-0.25224602  0.05533788  0.36997262]]
res [0.80360282 0.6728047  0.77894587]
sum [675.1522177  523.60018979 384.10540598]
p [[ 0.18305964 -0.0494661  -0.25224602]
 [-0.0494661   0.02447358  0.05533788]
 [-0.25224602  0.05533788  0.36997262]]
res [0.80360282 0.6728047  0.77894587]
sum [675.15775068 523.65531552 384.11429253]
p [[ 0.18305964 -0.0494661  -0.25224602]
 [-0.0494661   0.02447358  0.05533788]
 [-0.25224602  0.05533788  0.36997262]]
res [0.79964723 0.6743719  0.78388852]
theta_stimato [0.79964723 0.6743719  0.78388852]
best_respons

err 3.596646158900788
sum [683.45687046 530.92232537 388.7114255 ]
p [[ 0.18015665 -0.04868206 -0.24824779]
 [-0.04868206  0.02410509  0.05445345]
 [-0.24824779  0.05445345  0.36411373]]
res [0.78615728 0.69252538 0.77905931]
sum [683.45687046 530.92232537 388.7114255 ]
p [[ 0.18015665 -0.04868206 -0.24824779]
 [-0.04868206  0.02410509  0.05445345]
 [-0.24824779  0.05445345  0.36411373]]
res [0.78615728 0.69252538 0.77905931]
sum [685.36829315 532.97620455 389.69953814]
p [[ 0.18015665 -0.04868206 -0.24824779]
 [-0.04868206  0.02410509  0.05445345]
 [-0.24824779  0.05445345  0.36411373]]
res [0.78522895 0.70278849 0.77617903]
theta_stimato [0.78522895 0.70278849 0.77617903]
best_response() 1
id_arm 0
theta_stimato [0.78522895 0.70278849 0.77617903]
best_response() 1
id_arm 1
theta_stimato [0.78522895 0.70278849 0.77617903]
best_response() 1
id_arm 2
theta_stimato [0.78522895 0.70278849 0.77617903]
best_response() 1
id_arm 3
err 3.5926682180059086
sum [685.36829315 532.97620455 389.6995

best_response() 1
id_arm 0
theta_stimato [0.85959544 0.67201145 0.68188144]
best_response() 1
id_arm 1
theta_stimato [0.85959544 0.67201145 0.68188144]
best_response() 1
id_arm 2
theta_stimato [0.85959544 0.67201145 0.68188144]
best_response() 1
id_arm 3
err 3.5983012891104527
sum [693.26064684 538.61428642 394.01701116]
p [[ 0.17748632 -0.04789691 -0.24468561]
 [-0.04789691  0.02373143  0.05355055]
 [-0.24468561  0.05355055  0.35911518]]
res [0.83602381 0.67686977 0.70967545]
sum [693.26064684 538.61428642 394.01701116]
p [[ 0.17748632 -0.04789691 -0.24468561]
 [-0.04789691  0.02373143  0.05355055]
 [-0.24468561  0.05355055  0.35911518]]
res [0.83602381 0.67686977 0.70967545]
sum [695.23246164 538.873785   395.54912802]
p [[ 0.17748632 -0.04789691 -0.24468561]
 [-0.04789691  0.02373143  0.05355055]
 [-0.24468561  0.05355055  0.35911518]]
res [0.79867783 0.6706299  0.79130345]
theta_stimato [0.79867783 0.6706299  0.79130345]
best_response() 1
id_arm 0
theta_stimato [0.79867783 0.670629

theta_stimato [0.75571311 0.68003575 0.85550521]
best_response() 1
id_arm 0
theta_stimato [0.75571311 0.68003575 0.85550521]
best_response() 1
id_arm 1
theta_stimato [0.75571311 0.68003575 0.85550521]
best_response() 1
id_arm 2
theta_stimato [0.75571311 0.68003575 0.85550521]
best_response() 1
id_arm 3
err 3.5974045743212755
sum [704.76824805 546.26943856 401.21079898]
p [[ 0.17495017 -0.04719973 -0.24115121]
 [-0.04719973  0.02337357  0.05277456]
 [-0.24115121  0.05277456  0.35386109]]
res [0.76308057 0.67711696 0.84629901]
sum [704.76824805 546.26943856 401.21079898]
p [[ 0.17495017 -0.04719973 -0.24115121]
 [-0.04719973  0.02337357  0.05277456]
 [-0.24115121  0.05277456  0.35386109]]
res [0.76308057 0.67711696 0.84629901]
sum [707.26694419 548.01124972 402.53611525]
p [[ 0.17495017 -0.04719973 -0.24115121]
 [-0.04719973  0.02337357  0.05277456]
 [-0.24115121  0.05277456  0.35386109]]
res [0.79841323 0.6698345  0.80463657]
theta_stimato [0.79841323 0.6698345  0.80463657]
best_respons

sum [714.66048172 554.34899048 406.4703855 ]
p [[ 0.17298189 -0.04668071 -0.23847691]
 [-0.04668071  0.02312746  0.05219248]
 [-0.23847691  0.05219248  0.35000174]]
res [0.81211688 0.67452292 0.76816227]
sum [715.05598686 554.40104052 406.77769636]
p [[ 0.17298189 -0.04668071 -0.23847691]
 [-0.04668071  0.02312746  0.05219248]
 [-0.23847691  0.05219248  0.35000174]]
res [0.80481583 0.67330356 0.78411938]
theta_stimato [0.80481583 0.67330356 0.78411938]
best_response() 1
id_arm 0
theta_stimato [0.80481583 0.67330356 0.78411938]
best_response() 1
id_arm 1
theta_stimato [0.80481583 0.67330356 0.78411938]
best_response() 1
id_arm 2
theta_stimato [0.80481583 0.67330356 0.78411938]
best_response() 1
id_arm 3
err 3.5991282135855607
sum [715.05598686 554.40104052 406.77769636]
p [[ 0.17284681 -0.04670327 -0.23818168]
 [-0.04670327  0.02312369  0.05224178]
 [-0.23818168  0.05224178  0.34935647]]
res [0.81581197 0.67514004 0.76008632]
sum [715.05598686 554.40104052 406.77769636]
p [[ 0.17284681 

id_arm 0
theta_stimato [0.79382208 0.70676246 0.77959459]
best_response() 1
id_arm 1
theta_stimato [0.79382208 0.70676246 0.77959459]
best_response() 1
id_arm 2
theta_stimato [0.79382208 0.70676246 0.77959459]
best_response() 1
id_arm 3
err 3.5926120074335532
sum [731.03606378 568.44137537 415.66182098]
p [[ 0.17025611 -0.0460004  -0.23461466]
 [-0.0460004   0.02275749  0.05146322]
 [-0.23461466  0.05146322  0.34412482]]
res [0.79446575 0.6996402  0.78159463]
sum [731.03606378 568.44137537 415.66182098]
p [[ 0.17025611 -0.0460004  -0.23461466]
 [-0.0460004   0.02275749  0.05146322]
 [-0.23461466  0.05146322  0.34412482]]
res [0.79446575 0.6996402  0.78159463]
sum [731.06911932 568.77071213 415.71491177]
p [[ 0.17025611 -0.0460004  -0.23461466]
 [-0.0460004   0.02275749  0.05146322]
 [-0.23461466  0.05146322  0.34412482]]
res [0.77248816 0.70834673 0.80905791]
theta_stimato [0.77248816 0.70834673 0.80905791]
best_response() 1
id_arm 0
theta_stimato [0.77248816 0.70834673 0.80905791]
bes

In [817]:
#print(theta_stimato)
#print(Th[theta_vero[best_answer()]].vector)
#print(best_answer())
#print(best_arm())
#print(W)

[0.76734997 0.68864169 0.83512594]
[0.94931693 1.00341022 0.56391262]
0
0
[0.01867023724499146, 0.26435205148125446, 0.4087286108487782, 0.30824910042497594]


In [818]:
#print(theta_vero)

[0, 1, 2, 0, 0, 0]


In [819]:
R

[1.6393863227110328,
 -0.3039622614086742,
 1.4177977439235163,
 2.055292696617034,
 0.8065565953745695,
 1.1087287948906928,
 1.3206134833877083,
 0.9788961717437598,
 3.3076675272983644,
 -0.022014428433700328,
 1.124785769637388,
 1.4155790332216132,
 0.8400736172234187,
 1.1426713892894986,
 1.7610601439064346,
 1.8721736246292597,
 0.7652106198366248,
 0.4449889525875952,
 2.408230161002401,
 1.3868688067042199,
 1.304162557697834,
 0.6991949134834405,
 1.517103685665659,
 2.973507631915052,
 1.5270312757943247,
 1.4222285001524348,
 1.3316709451580087,
 0.7729284306401245,
 -1.0064893928330645,
 1.7019883870433254,
 1.6565127093350982,
 0.3761824266488729,
 1.8634215467330284,
 1.6841979981984976,
 1.3478806022520353,
 1.106539423774647,
 1.166470849944385,
 0.547913803324089,
 0.2655946583239268,
 2.519004991797327,
 2.1940172455509273,
 1.4052225944470829,
 1.4936386612620274,
 0.762335733190676,
 1.8803651052041133,
 2.971480929988515,
 0.46982777564724576,
 1.5867638259518526

In [820]:
N

[201, 201, 202, 202]

In [821]:
#print(sample_correct)

[0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [822]:
#print(error_reward)

[0.7656482605275898, 0.6056941523443753, 0.4421278949335927, 0.523546818648184, 0.46189257380563675, 0.6174488739125473, 0.5264716462016141, 0.513080390157709, 0.47372580597945113, 0.4222737409580197, 0.44074903206546767, 0.4846339079539148, 0.41243314868580283, 0.32448696377896646, 0.33809187051977996, 0.43694441268656314, 0.2501194477455042, 0.24005784252314255, 0.2393421868233978, 0.2722862254610068, 0.3147977951180967, 0.16603430516230433, 0.16268567091175612, 0.15877026217316192, 0.18807178773393085, 0.2308426211311585, 0.26213424388330786, 0.2475440965289506, 0.2802302198367794, 0.33862372510766203, 0.3292823871387367, 0.3173715550812364, 0.33535304637465213, 0.34092597310202044, 0.34070530980921543, 0.3726854591579021, 0.3621465838629081, 0.28855109608945817, 0.2787779771184149, 0.27863012058592806, 0.2975816180946398, 0.32142110881812247, 0.3159276038856276, 0.2676093998862399, 0.261955227865589, 0.2473836186753866, 0.24066373327775414, 0.22008182109973173, 0.22449664063384134,

In [823]:
#print(error_best_choosen)

[0.7656482605275898, 0.5563780101253377, 0.4421278949335927, 0.523546818648184, 0.46189257380563675, 0.5945669958434407, 0.048834030502862724, 0.047468981497109874, 0.054181404340937656, 0.04185512846864148, 0.16333734245328668, 0.1645818396775811, 0.17809013550058084, 0.1583141310907732, 0.2537340035856068, 0.23735627211471355, 0.2501194477455042, 0.24005784252314255, 0.2393421868233978, 0.2576147226501324, 0.25493755575139865, 0.16603430516230433, 0.16268567091175612, 0.15877026217316192, 0.15328189807824755, 0.18103167739630432, 0.15633962777526778, 0.13349391404017563, 0.10021323223369283, 0.13797447859917034, 0.14551249560642554, 0.12684903841732664, 0.10854993194543572, 0.11214409867395592, 0.11232550911676453, 0.1624643973736397, 0.17318407113856216, 0.12582580270269172, 0.13398781044149088, 0.13375589234455565, 0.11448830343209448, 0.12979995805796585, 0.13445007283096522, 0.0586322147734224, 0.06437820068498556, 0.055034232404510774, 0.06078920155100409, 0.028482888072554724, 

In [824]:
import numpy as np        
f=open('087029GAM.txt','a')
np.savetxt(f, error_reward, fmt='%1.3f', newline=", ")
f.write("\n")
np.savetxt(f, error_best_choosen, fmt='%1.3f', newline=", ")
f.write("\n")
np.savetxt(f, sample_correct, fmt='%1.3f', newline=", ")
f.write("\n")
f.close()